### ISSUE TITLE
I got postgress error - No function matches the given name and argument types....

### ISSUE THREAD

**Issue by gudata** [MiniProfiler/rack-mini-profiler#101]
When using select in sql I got an error

   @new_charities = Charity.select(:id, :name, :slug).published.where('created_at >= :since_date', since_date: since_date)

when I remove the select there is no error

   @new_charities = Charity.published.where('created_at >= :since_date', since_date: since_date)

here is a stack trace

https://gist.github.com/gudata/da2c5ce57ffd776179c6

I have tried with master and the latest released gem.

**Comment by gudata** [comment]
Correct, the generated sql query is wrong.

**Comment by kbrock** [comment]
@gudata as a followup, I've been converting most of my `Model.count` code over to `Model.count(:all)`
For us, the non-argument version is just too temperamental.
