### ISSUE TITLE
ERROR SystemStackError: stack level too deep in active_support_encoder.rb:17

### ISSUE THREAD

**Issue by emaillenin** [MiniProfiler/rack-mini-profiler#112]
When I add,

````ruby
gem 'rack-mini-profiler', require: false
````
in my Gemfile and

````ruby
if Rails.env == 'development'
  require 'rack-mini-profiler'

  # initialization is skipped so trigger it
  Rack::MiniProfilerRails.initialize!(Rails.application)
end
````
in my initializer, I get the following trace at the end of my Rails log for all requests and I do not see the Mini Profiler. App works fine though. 

````bash
[2014-12-01 20:28:23] ERROR SystemStackError: stack level too deep
	/Users/leninraj/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/set.rb:81
[2014-12-01 20:28:23] ERROR SystemStackError: stack level too deep
	/Users/leninraj/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/set.rb:81
[2014-12-01 20:28:23] ERROR SystemStackError: stack level too deep
	/Users/leninraj/.rvm/gems/ruby-2.1.2/bundler/gems/activesupport-json_encoder-072ab26faeaa/lib/active_support/json/encoding/active_support_encoder.rb:17
````

When I remove the gem and the initializer, I do not see this error in the trace. This is the code around [active_support_encoder.rb:17](https://github.com/chancancode/activesupport-json_encoder/blob/072ab26faeaa2ac083ca0aad36b47b57c9bffced/lib/active_support/json/encoding/active_support_encoder.rb#L15-L18)

````ruby
def initialize(options = nil)
  @options = options || {}
  @seen = Set.new
end
````

Here is my Gemfile:

````ruby
source 'https://rubygems.org'

ruby '2.1.2'

gem 'rails', '4.1.4'
gem 'pg'
gem 'haml'
gem 'haml-rails', '~> 0.5.3'
gem 'paperclip', '4.2.0'
gem 'font-awesome-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'jquery-ui-rails'
gem 'jbuilder', '~> 1.2'
gem 'devise'
gem 'simple_form'
gem 'merit', '~> 2.0'
gem 'icalendar'
gem 'kaminari'
gem 'rails-api'
gem 'piwik_analytics', '~> 1.0'
gem 'redis', '~> 3.0'
gem 'whenever'
gem 'omniauth'
gem 'slim-rails'
gem 'meta-tags'
gem 'tinymce-rails'
gem 'select2-rails'
gem 'js-routes'
gem 'pundit'
gem 'parsley-rails'
gem 'parsley_simple_form'
gem 'httpclient'
gem 'psych', '2.0.5'
gem 'twitter'
gem 'backbone-on-rails'
gem 'require_all'
gem 'activeadmin', github: 'activeadmin'
gem 'active_model_serializers', '~> 0.9.0'
gem 'activesupport-json_encoder', github: 'chancancode/activesupport-json_encoder'
gem 'sitemap_generator'
gem 'sass'
gem 'compass-rails' # should be in general group, not in assets
gem 'httparty'
gem 'capistrano'
gem 'capistrano-safe-deploy-to'
gem 'capistrano-unicorn-nginx'
# gem 'rack-mini-profiler', require: false
gem 'oj'
gem 'oj_mimic_json'

group :doc do
  gem 'sdoc', require: false
end

group :development do
  gem 'bullet'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rspec-rails'
  gem 'meta_request'
end

group :test do
  gem 'database_cleaner'
  gem 'capybara', '~> 2.2.0'
  gem 'selenium-webdriver'
  gem 'cucumber-rails', require: false
  gem 'capybara-select2'
  gem 'pickle'
  gem 'timecop'
  gem 'capypage', :path => 'vendor/gems/capypage-0.2.6'
end

group :development, :test do
  gem 'factory_girl_rails', '~> 4.0'
  gem 'pry'
end

group :assets do
  gem 'coffee-rails', '~> 4.0.0'
  gem 'uglifier', '>= 1.3.0'
end
````

What could be the issue? How do I get mini profiler to work?

**Comment by wesleyer** [comment]
This is what I'm getting.
Not sure if this is the same issue.

SystemStackError - stack level too deep:
11:14:08 web.1       |   rack-mini-profiler (0.9.2) lib/mini_profiler/page_timer_struct.rb:53:in `generate'
11:14:08 web.1       |   rack-mini-profiler (0.9.2) lib/mini_profiler/page_timer_struct.rb:53:in `to_json'
11:14:08 web.1       |   rack-mini-profiler (0.9.2) lib/mini_profiler/profiler.rb:121:in `serve_results'
11:14:08 web.1       |   rack-mini-profiler (0.9.2) lib/mini_profiler/profiler.rb:144:in `serve_html'
11:14:08 web.1       |   rack-mini-profiler (0.9.2) lib/mini_profiler/profiler.rb:201:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   rack (1.5.2) lib/rack/deflater.rb:25:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   versionist (1.3.0) lib/versionist/middleware.rb:39:in `_call'
11:14:08 web.1       |   versionist (1.3.0) lib/versionist/middleware.rb:17:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
11:14:08 web.1       |   warden (1.2.3) lib/warden/manager.rb:34:in `catch'
11:14:08 web.1       |   warden (1.2.3) lib/warden/manager.rb:34:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   rack (1.5.2) lib/rack/etag.rb:23:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   rack (1.5.2) lib/rack/head.rb:11:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   actionpack (4.0.13) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   actionpack (4.0.13) lib/action_dispatch/middleware/flash.rb:241:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
11:14:08 web.1       |   rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   actionpack (4.0.13) lib/action_dispatch/middleware/cookies.rb:486:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   activerecord (4.0.13) lib/active_record/query_cache.rb:36:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   activerecord (4.0.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   activerecord (4.0.13) lib/active_record/migration.rb:373:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
11:14:08 web.1       |   activesupport (4.0.13) lib/active_support/callbacks.rb:373:in `_run__2791909282382737623__call__callbacks'
11:14:08 web.1       |   activesupport (4.0.13) lib/active_support/callbacks.rb:80:in `run_callbacks'
11:14:08 web.1       |   actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   actionpack (4.0.13) lib/action_dispatch/middleware/reloader.rb:64:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   actionpack (4.0.13) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
11:14:08 web.1       |   better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
11:14:08 web.1       |   better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   actionpack (4.0.13) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   actionpack (4.0.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   railties (4.0.13) lib/rails/rack/logger.rb:38:in `call_app'
11:14:08 web.1       |   railties (4.0.13) lib/rails/rack/logger.rb:20:in `block in call'
11:14:08 web.1       |   activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `block in tagged'
11:14:08 web.1       |   activesupport (4.0.13) lib/active_support/tagged_logging.rb:26:in `tagged'
11:14:08 web.1       |   activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `tagged'
11:14:08 web.1       |   railties (4.0.13) lib/rails/rack/logger.rb:20:in `call'
11:14:08 web.1       |   quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   actionpack (4.0.13) lib/action_dispatch/middleware/request_id.rb:21:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   rack (1.5.2) lib/rack/runtime.rb:17:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   activesupport (4.0.13) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   rack (1.5.2) lib/rack/lock.rb:17:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   actionpack (4.0.13) lib/action_dispatch/middleware/static.rb:84:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
11:14:08 web.1       |   rack-cache (1.2) lib/rack/cache/context.rb:143:in `pass'
11:14:08 web.1       |   rack-cache (1.2) lib/rack/cache/context.rb:155:in `invalidate'
11:14:08 web.1       |   rack-cache (1.2) lib/rack/cache/context.rb:71:in `call!'
11:14:08 web.1       |   rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   rack-timeout (0.1.1) lib/rack/timeout.rb:104:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   railties (4.0.13) lib/rails/engine.rb:511:in `call'
11:14:08 web.1       |   railties (4.0.13) lib/rails/application.rb:97:in `call'
11:14:08 web.1       |   newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
11:14:08 web.1       |   passenger (4.0.57) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
11:14:08 web.1       |   passenger (4.0.57) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
11:14:08 web.1       |   passenger (4.0.57) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
11:14:08 web.1       |   passenger (4.0.57) lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
11:14:08 web.1       | App 29025 stderr: cache: [POST /mini-profiler-resources/results] invalidate, pass

**Comment by akshetpandey** [comment]
+1. Also, the ruby process hangs in what seems like an infinite loop. Also, the POST for result never returns, making both the server and the gem unusable.

```
INFO  : Completed 200 OK in 6381ms (Views: 4865.7ms | ActiveRecord: 879.7ms)


INFO  : Started GET "/mini-profiler-resources/includes.js?v=898a13ca6797c6bc1fee313e17d388b0" for 127.0.0.1 at 2015-01-19 19:54:59 +0530


INFO  : Started GET "/mini-profiler-resources/includes.css?v=898a13ca6797c6bc1fee313e17d388b0" for 127.0.0.1 at 2015-01-19 19:55:01 +0530


INFO  : Started GET "/mini-profiler-resources/jquery.tmpl.js?v=898a13ca6797c6bc1fee313e17d388b0" for 127.0.0.1 at 2015-01-19 19:55:01 +0530


INFO  : Started POST "/mini-profiler-resources/results" for 127.0.0.1 at 2015-01-19 19:55:01 +0530
FATAL : 
SystemStackError - stack level too deep:
  actionpack (4.1.6) lib/action_dispatch/middleware/reloader.rb:79:in `'



INFO  : Started POST "/mini-profiler-resources/results" for 127.0.0.1 at 2015-01-19 19:55:02 +0530
FATAL : 
SystemStackError - stack level too deep:
  actionpack (4.1.6) lib/action_dispatch/middleware/reloader.rb:79:in `'


INFO  : Started POST "/mini-profiler-resources/results" for 127.0.0.1 at 2015-01-19 19:55:02 +0530
```

My Gemfile

```
source 'https://rubygems.org'

#--------------------------------------
# DEFAULT GEMS
#--------------------------------------

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.6'
# Use mysql as the database for Active Record
gem 'mysql2', '0.3.17'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails', '~> 3.1'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks', '~> 2.5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

#--------------------------------------
# Added Gems
#--------------------------------------

gem 'autoprefixer-rails', '~> 4.0'
gem 'aws-sdk', '~> 1.0'
gem 'bootstrap-sass', '~> 3.2'
gem 'devise', '~> 3.4'
gem 'docker-api', '~> 1.17', :require => 'docker'
gem 'exception_notification', '~> 4.0'
gem 'fast_blank'
gem 'i18n-js', '~> 2.1'
gem 'jquery-ui-rails' , '~> 5.0'
gem 'koala', '~> 1.10'
gem 'mono_logger'
gem 'oj'
gem 'oj_mimic_json'
gem 'omniauth-facebook', '~> 2.0'
gem 'paperclip', '~> 4.2'
gem 'resque', '~> 1.25'
gem 'hiredis'
gem 'redis', require: %w(redis redis/connection/hiredis)
gem 'resque-scheduler', '~> 4.0'
gem 'sanitize', '~> 3.0'
gem 'tinymce-rails', '~> 4.1'

#--------------------------------------
# Development Only Gems
#--------------------------------------

group :development, :test do
  gem "awesome_print"
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'dotenv-rails'
  gem 'flamegraph'
  # Install this manually using `gem install mailcatcher` and then run `mailcatcher` in the background to have the SMTP server running.
  # gem 'mailcatcher'
  gem 'mock_redis'
  gem 'pry'
  gem 'quiet_assets'
  gem 'rack-mini-profiler', require: false
  gem 'stackprof'
end

```

**Comment by seanlinsley** [comment]
Ruby's JSON serialization doesn't handle circular references, which is why another gem I've worked on [included their own implementation](https://github.com/getsentry/raven-ruby/pull/118).

Though in this situation we control all of the data, so we should be able to get rid of the circular reference instead of resorting to that.

**Comment by zapo** [comment]
I fixed it naively by monkey patching `TimerStruct::Base` with:

```
module Rack
  class MiniProfiler
    module TimerStruct
      class Base
        def as_json
          @attributes
        end
      end
    end
  end
end
```

**Comment by wojtha** [comment]
@SamSaffron I put together solutions from @emaillenin @zapo and I'm able to finally use Oj and Miniprofiler together. Thank you guys!

**Gemfile**
```ruby
gem 'rack-mini-profiler', group: 'development', require: false 
```

**config/initializers/miniprofiler.rb**
```ruby
if Rails.env.development?
  require 'rack-mini-profiler'

  # Fix circular ref conflict with Oj.mimic_json
  module Rack
    class MiniProfiler
      module TimerStruct
        class Base
          def as_json
            @attributes
          end
        end
      end
    end
  end

  # Initialization is skipped so trigger it
  Rack::MiniProfilerRails.initialize!(Rails.application)
end
```

**Comment by kbrock** [comment]
So is the thought to add this monkey patch directly to the source? Or to put in a patch to oj? Or modify our data structure to remove the circular dependency?

**Comment by peterkeen** [comment]
Bump. I would lean toward removing the circular dependency.

**Comment by dgynn** [comment]
The circular dependency was removed in #250 and is fixed on master. This issue can probably be closed.
