### ISSUE TITLE
Stack when I want the detail on sql requests

### ISSUE THREAD

**Issue by casertap** [MiniProfiler/rack-mini-profiler#113]
When I click on "1 sql" to have the details of the request, I get this stack:

/Users/pierrecaserta/.rvm/gems/ruby-1.9.3-p551/gems/rack-mini-profiler-0.9.2/lib/mini_profiler/request_timer_struct.rb:75:in `new'
/Users/pierrecaserta/.rvm/gems/ruby-1.9.3-p551/gems/rack-mini-profiler-0.9.2/lib/mini_profiler/request_timer_struct.rb:75:in`add_sql'
/Users/pierrecaserta/.rvm/gems/ruby-1.9.3-p551/gems/rack-mini-profiler-0.9.2/lib/mini_profiler/profiling_methods.rb:8:in `record_sql'
/Users/pierrecaserta/.rvm/gems/ruby-1.9.3-p551/gems/rack-mini-profiler-0.9.2/lib/patches/sql_patches.rb:50:in`query'
/Users/pierrecaserta/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
/Users/pierrecaserta/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:280:in`block in log'
/Users/pierrecaserta/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/pierrecaserta/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:275:in`log'

**Comment by sachin21** [comment]
+1
