### ISSUE TITLE
Mounted Routes

### ISSUE THREAD

**Issue by kamilpogo** [MiniProfiler/rack-mini-profiler#114]
rack-mini-profiler doesn't work with mounted routes like
```ruby
namespace :admin do
  mount Resque::Server, :at => 'resque'
end
```
It inject html that tries to load "/admin/resque/mini-profiler-resources/includes.js" which cannot be found because it serves "/mini-profiler-resources/includes.js"

**Comment by albertodega** [comment]
same here! +1

**Comment by TrevorS** [comment]
:+1:

**Comment by brodock** [comment]
:+1: same here

**Comment by ballou88** [comment]
This seems to happen for engines that have mounted routes.  It was introduced with https://github.com/MiniProfiler/rack-mini-profiler/commit/29aac5d4.

I don't fully understand what this commit was trying to accomplish.  If anyone can give me a little insight maybe I can work up a pull request.  Thanks.

**Comment by smarterclayton** [comment]
It was to support rack apps that were not running at the root, ie within passenger you can define a prefix string (/app) that when your rack app gets invoked (/app/bar), the request path rack sees is /bar and an env SCRIPT_NAME "/app".  This is supported in Rails, but somewhat spotty.  I don't have an immediate guess why the namespace would break it - I believe at the time we also were using namespaces but may not have been a mounted engine under a namespace.

**Comment by brodock** [comment]
any updates on the issue?
It looks like that even skip_paths are not working for this specific issue.

**Comment by haggen** [comment]
Almost a year and nothing? :'(

**Comment by SamSaffron** [comment]
I am sad too, but someone is going to need to work on this I merged one attempted fix in this department and it is already showing cracks. 

Subdirectory installs in rails and rack follow weird conventions
