### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by avokhmin** [MiniProfiler/rack-mini-profiler#118]
Since 0.9.2, there's been a handful of useful commits... Would be nice to get it released as a gem version 0.9.3 so it doesn't have to come from git...

**Comment by SamSaffron** [comment]
I want to update but am very worried about regressions, its a massive amount of change there. Will try to get to it this month when I get back from vacation

**Comment by recurser** [comment]
+1

**Comment by lukad** [comment]
+1

**Comment by salimane** [comment]
+1

**Comment by cheriot** [comment]
+1

**Comment by SamSaffron** [comment]
I release 0.9.3 just now
