### ISSUE TITLE
getting multiple favicon requests when using mini-profiler (Firefox)

### ISSUE THREAD

**Issue by brodock** [MiniProfiler/rack-mini-profiler#119]
Whenever I use mini-profiler with firefox, I get multiple favicon requests (one for each ajax call).

![favicon requests](https://cloud.githubusercontent.com/assets/20575/5628886/3ec123ae-9594-11e4-96b5-c3e7b628af22.png)

I understand that this may not be related to mini-profiler in anyway, and may be a bug with Firefox or with jQuery ajax call, but I want to know if I'm the only one experiencing this and if anyone found a workaround.

**Comment by SamSaffron** [comment]
its probably doing so cause you have no favicon file per ajax call ... have you tried adding favicon.ico to your assets?

**Comment by kbrock** [comment]
Agreed, this is part of the behavior of the browser.

You can either fix, or just add `favicon.ico` to the ignore list (hide the problem)

**Comment by SamSaffron** [comment]
Yeah ... nothing much we can do here
