### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by davetoxa** [MiniProfiler/rack-mini-profiler#124]
Readme has a broken link 
`Cleaning up the horrendous class structure that is using strings as keys and crazy non-objects`

**Comment by SamSaffron** [comment]
PR to fix?

**Comment by davetoxa** [comment]
It's already cleaned or need to fix the link? I found this file [here](https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/mini_profiler/timer_struct/sql.rb)

**Comment by davydovanton** [comment]
@SamSaffron you forget close this issue :tada:
