### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hotkeys' of undefined

### ISSUE THREAD

**Issue by mockdeep** [MiniProfiler/rack-mini-profiler#129]
I'm not sure if this is an error in my application or dependencies, but I've started seeing this error on my javascript console from `MiniProfiler`:

```
Uncaught TypeError: Cannot read property 'hotkeys' of undefined    includes.js?v=9db1f8db18400644bd5c7449e5295620:666
MiniProfiler.init.init                                             includes.js?v=9db1f8db18400644bd5c7449e5295620:666
MiniProfiler.init.deferInit                                        includes.js?v=9db1f8db18400644bd5c7449e5295620:657
```

I've got `jQuery` required in my `application.js` file.  I'm on Rails `4.2.0` and Ruby `2.1.5`, rack-mini-profiler `0.9.3`. Happy to post my Gemfile.lock or anything else you need to see.

**Comment by pex** [comment]
Same here

**Comment by zhengpd** [comment]
This issue is stale and should be closed. There is no `hotkeys` property accessing in `includes.js` anymore.
