### ISSUE TITLE
profiler works locally but not on server

### ISSUE THREAD

**Issue by therrick** [MiniProfiler/rack-mini-profiler#131]
The profiler is working great for me locally, but I'm trying to get it work in a deployed server environment (called 'edge'). The mini-profiler doesn't appear on the page, and appending ?pp=help to the URL does nothing in the server environment. Both work fine in my local development environment.

Reading some discussions, I thought it might be a file permissions issue on the tmp/miniprofiler directory, so I created an initializer to set the storage, but it didn't help.
`Rack::MiniProfiler.config.storage = Rack::MiniProfiler::MemoryStore`

I've confirmed that Rack::MiniProfiler is in the middleware stack...
```
[root@ip-10-163-1-90 current]# RAILS_ENV=edge bundle exec rake middleware
use Rack::MiniProfiler
use Rack::Sendfile
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x0000000177b5e0>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Callbacks
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
run ClientTracker::Application.routes
```

I also confirmed with rails console that my initializer is working:
```
$: rails c
Loading edge environment (Rails 4.1.8)
2.1.5 :001 > Rack::MiniProfiler.config.storage
 => Rack::MiniProfiler::MemoryStore
```

There are no errors in the rails log, and nothing in the javascript console on the browser.

Gemfile is here: https://gist.github.com/therrick/b8a60031b66cf5f74e21

Gemfile.lock is here: https://gist.github.com/therrick/58d1ca1dd397ce80cd10

Any idea what I might be doing wrong here?

**Comment by SamSaffron** [comment]
In production you must approve all requests, see readme "Access control in production"

**Comment by therrick** [comment]
Thanks for the quick response, Sam. From the readme, I thought that only applied to the literal RAILS_ENV=production environment.  Now that I look at the source code I see that only the 'development' and 'test' environments are authorized by default.

I ended up adding the following to application_controller and it is working now.

  before_action :authorize_mini_profiler
  ...
  def authorize_mini_profiler
    if %w(staging edge).include?(Rails.env)
      Rack::MiniProfiler.authorize_request
    end
  end
