### ISSUE TITLE
Enabling and disabling is broken in production environment

### ISSUE THREAD

**Issue by dalibor** [MiniProfiler/rack-mini-profiler#134]
I want to have `rack-mini-profiler` disabled by default and be able to enable it with `?pp=enable`.

In Gemfile:

``` ruby
gem 'flamegraph'
gem 'rack-mini-profiler'
```

In initializer:

``` ruby
Rack::MiniProfiler.config.enabled = false
```

In ApplicationController:

``` ruby
before_filter :enable_profiler
def enable_profiler
  if is_admin? && (params[:pp] == 'enable' || !!cookies[:profiler_enabled])
    cookies[:profiler_enabled] = true
    Rack::MiniProfiler.authorize_request
  end
end

def is_admin?
  true
end
```

In `config/environments/production.rb`:

``` ruby
config.serve_static_files = true
config.assets.compile = true
```

In development environment it works as expected. By default, it's disabled. I can enable it with `?pp=enable`, disable it with `?pp=disable`, etc.

In production environment it does not work as expected. It's disabled by default, but I cannot enable it with `?pp=enable`. Also, if I remove the initializer, then the profiler shows, but it shows on the second page refresh which seems as not expected? Then I can disable it with `?pp=disable` but cannot enable it again. So, something is funky and it's not consistent with how enable/disable works in development environment.

**Comment by vlad-ninja** [comment]
Having same issue. Trying to enable profiler on staging server with before filter:

```
Rack::MiniProfiler.authorize_request if Rails.env.staging?
```

But it is not working. Are there any other ways  to enable profiler not in development env?

**Comment by nateberkopec** [comment]
Hm, it works fine for me on Ruby 2.2.2 and Rails 4.2.

FWIW, I don't call `Rack::MiniProfiler.config.enabled = false` anywhere, nor do I ever use `?pp=enable`.

**Comment by EtienneDepaulis** [comment]
Same problem here in staging and production environments :/
I use:
```
def check_rack_mini_profiler
  if admin_user_signed_in?
    Rack::MiniProfiler.authorize_request
  end
end
```

When an `AdminUser` is logged in (and only then) I can access ?pp=help and access all the GC/flamegraph options.
However I can't display the badge :/ (I checked in `/tmp/miniprofiler/`and my request generates `mp_timers_n9s9fe6767...` files)
It looks like it is only a display problem (it works just fine in development)

Any ideas ? (I have no initializer and all necessary gems are in the Gemfile without any group restrictions)

**Comment by EtienneDepaulis** [comment]
I finally found the solution :/

I had to use this initializer:
```
require 'rack-mini-profiler'

Rack::MiniProfilerRails.initialize!(Rails.application)

if Rails.env.production? or Rails.env.staging?
  Rails.application.middleware.delete(Rack::MiniProfiler)
  Rails.application.middleware.insert_after(Rack::Deflater, Rack::MiniProfiler)
end
```

Everything is working fine now :)

**Comment by nateberkopec** [comment]
@dalibor @EtienneDepaulis Right, if you're using Rack::Deflater (or any other number of "gzip" gems that may use it) you need to make sure Rack::MiniProfiler is inserted in the correct order.

Otherwise RMP will try to insert html into an already-gzipped response, which isn't gonna work.

**Comment by nateberkopec** [comment]
> Also, if I remove the initializer, then the profiler shows, but it shows on the second page refresh which seems as not expected? 

FWIW, I've also seen this behavior. I don't know what's up with that.

**Comment by dalibor** [comment]
Just tested it on another application (Rails 4.2.1) and it works as expected per my description in this issue. The application where it does not work as expected is Rails 3.1.3.

**Comment by dalibor** [comment]
Did some more testing with different rails versions and here are my findings.

**Rails 3.1.3** (tested in 2 different applications and getting the same behavior)

Scenario 1:

1. Stop and start the server in production environment. Close and reopen browser.
2. Open http://localhost:3000 # not enabled -- good
3. Open http://localhost:3000/?pp=enable # does not enables it -- bug
4. Open http://localhost:3000 # not enabled
5. Open http://localhost:3000/?pp=enable # not enabled
6. Open http://localhost:3000/?pp=enable # not enabled, and from now on I can never enable it for this browser session

Scenario 2:

1. Close and reopen Firefox
2. Open http://localhost:3000 # not enabled -- good
3. Open http://localhost:3000/?pp=enable # not enabled -- bug
4. Open http://localhost:3000/?pp=enable # now it gets enabled; fine

Scenario 3:

Setup: Ensure that you have successfully run scenario 2 before this one and server wasn't restarted.

1. Close and reopen Firefox
2. Open http://localhost:3000 # not enabled -- good
3. Open http://localhost:3000/?pp=enable # not enabled -- bug
4. Open http://localhost:3000 # enabled -- different from behavior in Scenario 1, step 4 (server wasn't restarted and scenario 2 was run prior to this one)

**Rails 4.2.1**

Scenario 4:

1. Stop and start the server in production environment. Close and reopen Firefox.
2. Open http://localhost:3000 # not enabled -- good
3. Open http://localhost:3000/?pp=enable # not enabled -- bug
4. Open http://localhost:3000 # still not enabled
5. Open http://localhost:3000/?pp=enable # now it gets enabled

Scenario 5:

Setup: Ensure that you have successfully run scenario 4 before this one and server wasn't restarted.

1. Close and reopen Firefox
2. Open http://localhost:3000 # not enabled -- good
3. Open http://localhost:3000/?pp=enable # enabled -- different behavior from Scenario 4, step 3 (server wasn't restarted and scenario 4 was run prior to this one)

**Comment by steverob** [comment]
Still the same issue for me. Here is my setup - 

*Gemfile*
```ruby
gem 'rack-mini-profiler'
  gem 'flamegraph'
  gem 'stackprof'
```

*initializers/mini_profiler.rb*
```ruby
require 'rack-mini-profiler'
Rack::MiniProfilerRails.initialize!(Rails.application)
```

But nothing shows when running app in production mode.

Then I added (updated to my authorization setup) this to AppCtrlr - 
```ruby
before_action do
    if current_user && current_user.is_admin?
      Rack::MiniProfiler.authorize_request
    end
  end
```
And still nothing shows up. Would appreciate some help :)

Also, I tried - 
```ruby
if Rails.env.production? or Rails.env.staging?
  Rails.application.middleware.delete(Rack::MiniProfiler)
  Rails.application.middleware.insert_after(Rack::Deflater, Rack::MiniProfiler)
end
```

But it turns out I do not have the `Deflator` middleware. So I did not know where to insert the Miniprofiler middlewhere.

Environment - 
Ruby: `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]`
Rails: `4.2.6`
MiniProfiler: `0.10.1`

**Comment by jclusso** [comment]
My setup works fine in development but in staging I can't get it to work. The only way I can get it to show the badge is if I use the default storage. Once I enable RedisStore it breaks even though RediStore works fine in development.

**Comment by nateberkopec** [comment]
Closing as stale, but I encourage anyone with a "my RMP doesn't show up" problem to open a new issue.

**Comment by adamreisnz** [comment]
I was able to disable this conditionally using a new initializer as follows:

```
require 'rack-mini-profiler'

if Rails.env.development? && ENV['DISABLE_RACK_MINI_PROFILER'] == 'true'
  Rails.application.middleware.delete(Rack::MiniProfiler)
end
```

**Comment by tomdonarski** [comment]
Since this was top result in google, what helped me was `.move_after` ([docs](https://api.rubyonrails.org/classes/Rails/Configuration/MiddlewareStackProxy.html#method-i-move_after)).
```
if Rails.env.production?
  Rails.application.middleware.move_after(Rack::TempfileReaper, Rack::MiniProfiler)
end
```
I'm on
