### ISSUE TITLE
X-MiniProfiler-Ids are being set only if response status is 200

### ISSUE THREAD

**Issue by sooryazeal** [MiniProfiler/rack-mini-profiler#143]
I have an API application that returns different status codes - 200, 204, 201 for successful requests. I'm using the X-MiniProfiler-Ids to access the JSON requests' profile. But the 'X-MiniProfiler-Ids' are present only if response status is 200.
https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/mini_profiler/profiler.rb#L331
```
if headers['Content-Type'] && status == 200
    client_settings.write!(headers)
    result = inject_profiler(env,status,headers,body)
    return result if result
end
```
```
def inject_profiler(env,status,headers,body)
    ...
    # inject header
    if headers.is_a? Hash
        headers['X-MiniProfiler-Ids'] = ids_json(env)
    end
    ...
end
```
I think this line should be changed to accept all 2xx status codes.

**Comment by SamSaffron** [comment]
Sure, PR to fix this welcome.

**Comment by kbrock** [comment]
I think this is fixed [here](https://github.com/MiniProfiler/rack-mini-profiler/blob/c0f4d7c01d6af7b6fa4719e9ae33f0c0132da1ea/lib/mini_profiler/profiler.rb#L339) - can this be closed?

**Comment by SamSaffron** [comment]
sure... closing ... thanks
