### ISSUE TITLE
Assets do not load without `require_tree .`

### ISSUE THREAD

**Issue by voltechs** [MiniProfiler/rack-mini-profiler#147]
When I remove `//= require_tree .` from my application.js file, the mini-profiler tab in the top left no longer renders/shows.

I've searched high and low including digging through some of the codebase to find a way to explicitly require the asset files needed for the profiler tab to show, but have been unsuccessful.

Please put instructions in the readme on how to accomplish this. Removing `require_tree .` can be a huge performance factor which is the concern of rack-mini-profiler so it shouldn't be require especially in the spirit of trying to track down bottle-necks.

Thanks!

**Comment by nateberkopec** [comment]
> Removing require_tree . can be a huge performance factor

Huh? Are you compiling assets in production? 

I don't know why this is happening, though - it seems strange to me because I thought RMP inserted its own assets via a Rack middleware, which should have nothing to do with your application.js.

**Comment by kbrock** [comment]
I verified that my assets are being returned from the rack middleware. (I wouldn't mind turning this off but ...)

**Comment by kbrock** [comment]
I think the issue may be you are using an assets host?

**Comment by SamSaffron** [comment]
I would strongly recommend against bundling MiniProfiler JS with the rest of your applications js. You should not need to add anything to your application.js file to get it to work. 

Perhaps somehow you are not allowing through js requests to the routes mini profiler is serving, there has to be a 404 somewhere, have a look in dev tools

**Comment by kbrock** [comment]
Also, if you are using apache up front it may be pointing your js to your assets directory rather than going to your rails app.

**Comment by SamSaffron** [comment]
I don't know what to do here, closing
