### ISSUE TITLE
Runs mkdir in tmp even when not using FileStore

### ISSUE THREAD

**Issue by maxim** [MiniProfiler/rack-mini-profiler#152]
Is it necessary to do this when FileStore isn't configured?
https://github.com/MiniProfiler/rack-mini-profiler/blob/f4d12ae8b621c7bd7762bcd67208ff964858f777/lib/mini_profiler_rails/railtie.rb#L43

In our production servers the app doesn't have permissions under tmp/, so we get an error on startup. I wonder if this would be an easy fix. Awesome tool, can't wait to start seeing performance stats. :+1:

**Comment by jcblitz** [comment]
To add to this comment, doesn't line #47 just ignore whatever storage was passed in on the config and uses FileStore?

**Comment by maxim** [comment]
@jcblitz I believe it sets up defaults that you later change in your own initializers. Except that the line I highlighted above actually does something destructive before anything can be changed.

**Comment by kbrock** [comment]
Is there a suggestion on how to fix?

**Comment by kbrock** [comment]
@maxim Think this should be all set. re-open / ping if it is not
Thanks

**Comment by maxim** [comment]
@kbrock looks good to me, appreciate the fix! Happy to see it finally resolved.
