### ISSUE TITLE
HTTP_IF_MODIFIED_SINCE is set to empty string rather than nil

### ISSUE THREAD

**Issue by DangerDawson** [MiniProfiler/rack-mini-profiler#153]
The problem is that  env['HTTP_IF_MODIFIED_SINCE']  is being set to an empty string, which in turn breaks the conditionalget in rack ( see below ), should it not be set to nil?

so in lib/mini_profiler/profiler.rb

```
      # Strip all the caching headers so we don't get 304s back
        #  This solves a very annoying bug where rack mini profiler never shows up
        if config.disable_caching
          env['HTTP_IF_MODIFIED_SINCE'] = ''
          env['HTTP_IF_NONE_MATCH']     = ''
        end
```

rack-1.5.5/lib/rack/conditionalget.rb

```
    def fresh?(env, headers)
      modified_since = env['HTTP_IF_MODIFIED_SINCE']
      none_match     = env['HTTP_IF_NONE_MATCH']

      return false unless modified_since || none_match

      success = true
      success &&= modified_since?(to_rfc2822(modified_since), headers) if modified_since
      success &&= etag_matches?(none_match, headers) if none_match
      success
    end
```

**Comment by SamSaffron** [comment]
It is breaking it on purpose, while mini profiler is enabled we work hard to ensure no caching is performed.

You are only meant to enable it on admin accounts, they can live with the limited caching while mp is running (and always can opt out from mini profiler use the help link to see how.)
