### ISSUE TITLE
rack-mini-profiler causing app to freeze after one request

### ISSUE THREAD

**Issue by tylereaves** [MiniProfiler/rack-mini-profiler#16]
Just built a new Fedora 19 system.

Rails 4.0.1rc2, Ruby 2.0p247

The very first request to my app (in development mode) works fine, all others fail, the rails process is deadlocked in a Futex. If I disable the rack-mini-profiler gem this doesn't happen. 

Edit: Just tried with Rails 4.0.0, same behavior.

**Comment by dahal** [comment]
+1, I'm having the same exact issue. I have `Oj.mimic_JSON` on `initializers/oj.rb` and 

```
group :development do
  gem 'rack-mini-profiler'
end
```

**Comment by byterussian** [comment]
Me too, rails 4.1.9 and ruby 2.1.2. Gems:
```
gem 'oj'
gem 'oj_mimic_json'
```

**Comment by michaelorr** [comment]
This is still an issue for me as well... Any ideas on the root cause or a possible solution?

**Comment by agrass** [comment]
same problem with rails 4.1.11. any workaround for this? anyone know if be a trouble use oj without oj_mimic_json?

**Comment by nateberkopec** [comment]
Closing as stale, please leave a comment if this is still something you would like to see addressed.
