### ISSUE TITLE
Unable to make the profiler work in production mode

### ISSUE THREAD

**Issue by marvindanig** [MiniProfiler/rack-mini-profiler#168]
I tried the `require: false` on the Gemfile and then initialized with `config/initializers/rack_profiler.rb` as explained in the READMe. Also tried other solutions on the web like placing the following on `config.ru`:

```
require 'rack-mini-profiler'
use Rack::MiniProfiler
```
or the following on `config/production`:

```
config.middleware.use Rack::Deflater
```
I'm on ruby 2.2.2p95 and rails 4.2.3.

**Comment by marvindanig** [comment]
Okay I got this working, but only on Firefox in production mode. 

The profiler doesn't appear on -webkit browsers, tried both on Chrome & Safari. Let you know if this hints towards the underlying bug.

**Comment by jwgoh** [comment]
Have you tried this?

by @EtienneDepaulis
```ruby
require 'rack-mini-profiler'

Rack::MiniProfilerRails.initialize!(Rails.application)

if Rails.env.production? or Rails.env.staging?
  Rails.application.middleware.delete(Rack::MiniProfiler)
  Rails.application.middleware.insert_after(Rack::Deflater, Rack::MiniProfiler)
end
```
https://github.com/MiniProfiler/rack-mini-profiler/issues/134#issuecomment-126647212

**Comment by marvindanig** [comment]
This :- 

```
ERROR -- : No such middleware to insert after: Rack::Deflater (RuntimeError)
/Users/admin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/stack.rb:125:in `assert_index'
/Users/admin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/stack.rb:96:in `insert_after'
/Users/admin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/configuration.rb:68:in `block in merge_into'
/Users/admin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/configuration.rb:67:in `each'
/Users/admin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/configuration.rb:67:in `merge_into'
/Users/admin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:501:in `app'
```

**Comment by andrewroth** [comment]
@marvindanig I'm having the same problem.  I was able to get it working by turning off ssl and using thin instead of unicorn with nginx.

Does rack mini profiler work in production mode with ssl?  One guide I was reading said it had to be turned off, but it didn't give any explanation beyond that.

Can you give me any help for how to find some clues about what's going on?  Where can I look in the code to see if the mini profiler JS is being inserted?  That way we can know if the problem is on the server or the client.

**Comment by marvindanig** [comment]
Hey @andrewroth I stopped trying after sometime, will take a dig at it next week. From as far as I remember, in `production` mode _mini_profiler_js wasn't being inserted into the dom on Google chrome.

It sorta worked on Firefox but I'll confirm that in a bit.

**Comment by andrewroth** [comment]
I got it working!  I had to turn off gzip in nginx.

**Comment by SamSaffron** [comment]
I am not understanding the bug here. 

@marvindanig  if you try to insert mini profiler after middleware that does not exist ... hmm .. it will not work. 

Try running 

```
rake routes
```

and insert it somewhere in your stack that makes sense, possibly even in position 0.

**Comment by olivierlacan** [comment]
@SamSaffron I think you meant `rake middleware`. Just adding that to help others.
