### ISSUE TITLE
QuotaExceededError when in Safari Incognito mode

### ISSUE THREAD

**Issue by jeffblake** [MiniProfiler/rack-mini-profiler#169]
This error: 

QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.

window.onerror·QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
/mini-profiler-resources/includes.js:36[unknown]

Gets triggered when in Safari Private browsing mode.

**Comment by gmcnaughton** [comment]
I think this error occurs when rack-mini-profiler accesses html5 local storage, and localStorage is disabled.

In Safari private browsing mode, localStorage must be disabled by default. (I get the same error when browsing in Safari in the iOS simulator).

**Comment by SamSaffron** [comment]
Should be easy to fix then by wrapping all access to local storage.

**Comment by kbrock** [comment]
Does this work if local storage is disabled?

**Comment by SamSaffron** [comment]
pretty sure this is fixed in latest, ping me if not (merged a fix in this department)
