### ISSUE TITLE
rack-mini-profiler badge not showing in rack app?

### ISSUE THREAD

**Issue by rchady** [MiniProfiler/rack-mini-profiler#176]
I was having a problem getting rack-mini-profiler working so I created a trivial rack app based on an example I saw

```
require 'rack'
require 'rack-mini-profiler'

use Rack::MiniProfiler
run Proc.new { |env| ['200', {'Content-Type' => 'text/html'}, [ "Hello!" ]] }

```

In loading this up, it seems like it does not work.. no badge, no nothing.  I finally tried ?pp=enable and I was then able to use ?pp=help at least, but still no badge of any kind showing.  

How do you get the badge to show in a rack app!?!?

**Comment by SamSaffron** [comment]
"hello!" is not really a valid html page ... try a valid html page.

**Comment by kbrock** [comment]
@rchady were you able to get this working?

For me, this worked:

```ruby
require 'rack-mini-profiler'

use Rack::MiniProfiler
run lambda { |env|
  [200, {'Content-Type' => 'text/html'}, ["<html><body>hello!</body></html>"]]
}
```

I'll put in a PR to make the readme better

**Comment by rchady** [comment]
I gave up for the moment.  My rack app replaces the entire return with dynamic content and for some reason the profiler block never got added no matter what I tried.  I'll return to this at a later date when I have time to work on it.

**Comment by kbrock** [comment]
@rchady cool. I did have trouble getting this to start. but once it started working had trouble getting it to fail.

For reference, I used the integration tests to track down my issues.
