### ISSUE TITLE
MiniProfiler with cached pages, encoding issue

### ISSUE THREAD

**Issue by ScotterC** [MiniProfiler/rack-mini-profiler#18]
````
!! Unexpected error while processing request: incompatible character encodings: ASCII-8BIT and UTF-8
````

When using full page caching.  After the page is written to disk with mini-profiler information, on the first attempt to read it back this error occurs.  It does not happen if mini-profiler is disabled.

**Comment by kbrock** [comment]
@ScotterC @jjb is this still an issue?

**Comment by jjb** [comment]
not sure, alas I haven't used it in years

**Comment by ScotterC** [comment]
@kbrock I don't think so. Will close
