### ISSUE TITLE
How can we disable a patch? We use Mongo but not Mongo::Server and it breaks.

### ISSUE THREAD

**Issue by amalagaura** [MiniProfiler/rack-mini-profiler#180]
I tried doing some manual initialization but I was not able to disable Mongo loading. This broke in 0.9.8 because it only tests for the existence of Mongo: 

```
if defined?(Mongo) &&!SqlPatches.patched? && SqlPatches.module_exists?("Mongo")
```

**Comment by SamSaffron** [comment]
Open to adding some switch to disable this, also if you require false in
the gemfile you can control the patching yourself.

**Comment by amalagaura** [comment]
Thanks I will try doing the patching myself. Setting SqlPatches.patched = true and doing the requires that I want.

**Comment by amalagaura** [comment]
OK it is not as simple as I thought because the error does not happen in the initalize! method. It happens as part of the requires. The code which causes the error is outside the class definition. So I cannot load the class SqlPatches because that triggers the requires.

Any thoughts on a strategy? Moving the requires as part of the initialize! seems to be necessary.

**Comment by SamSaffron** [comment]
hmmm is this simply a bug in the patcher, if its exploding on something
should it not check that it has everything it needs upfront?

**Comment by dgynn** [comment]
Could the check be changed to look for `Mongo::Server` instead of just `Mongo`?

**Comment by amalagaura** [comment]
@SamSaffron @dgynn Yes if it looks for `Mongo::Server` it should be sufficient. The error is that it cannot open `Mongo::Server`

**Comment by dalezak** [comment]
Running into this problem as well, if I specify 0.9.7 then it doesn't happen.

`gem 'rack-mini-profiler', '0.9.7'`

**Comment by SamSaffron** [comment]
Yes we want to sort this out and do another release PR welcome.

**Comment by dgynn** [comment]
It would be great if someone who uses Mongo::Server could create a patch and make sure it still works. Possibly @nofxx could do that.

Also, @niv and @janx might want to see if Riak and Nobrainer should check for a more specific constant definition if those could have similar problems.

**Comment by OsamaSayegh** [comment]
I'm assuming this is fixed because we now check for `Mongo::Server::Connection`:

https://github.com/MiniProfiler/rack-mini-profiler/blob/60fb0d5be650efe6f387bbce847dc3d8049e652f/lib/patches/sql_patches.rb#L51

I'm going to close this but do let me know if it's still an issue and I'll reopen/investigate.
