### ISSUE TITLE
ArgumentError: comparison of String with 200 failed

### ISSUE THREAD

**Issue by paweljw** [MiniProfiler/rack-mini-profiler#185]
Hi,

This error in the title happens on every request. Despite that, MiniProfiler seems to work and produce meaningful results. Also this doesn't happen in the development environment, only in staging (and production, when MiniProfiler is configured to run there).

Here's a complete stack trace of an example error:

```
[2016-01-06 11:48:39] ERROR ArgumentError: comparison of String with 200 failed
  /home/someuser/.rvm/gems/ruby-2.2.1@rails4.2/gems/rack-mini-profiler-0.9.8/lib/mini_profiler/profiler.rb:294:in `>='
  /home/someuser/.rvm/gems/ruby-2.2.1@rails4.2/gems/rack-mini-profiler-0.9.8/lib/mini_profiler/profiler.rb:294:in `call'
  /home/someuser/.rvm/gems/ruby-2.2.1@rails4.2/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
  /home/someuser/.rvm/gems/ruby-2.2.1@rails4.2/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
  /home/someuser/.rvm/gems/ruby-2.2.1@rails4.2/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
  /home/someuser/.rvm/gems/ruby-2.2.1@rails4.2/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
  /home/someuser/.rvm/gems/ruby-2.2.1@rails4.2/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
  /home/someuser/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /home/someuser/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /home/someuser/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

Reading the code in profiler.rb, it seems that the offending line is

```ruby
if status >= 200 && status < 300 && ((Time.now - start) > 0.1)
```

so obviously I tried the most obvious fix I could: I forked rack-mini-profiler and forced a cast to integer there, so that the line reads

```ruby
if status.to_i >= 200 && status.to_i < 300 && ((Time.now - start) > 0.1)
```

The fix is contained in https://github.com/paweljw/rack-mini-profiler/tree/status-error-fix on my side, and this is what we're using right now in our projects. It eliminates the error, works fine (as in - the same as it worked before) and passes rack-mini-profiler's spec. 

I'm curious, however - could this be caused by something (some other gem, or configuration setting) on our side? Is there something that can force status to be a string (since it was obviously an integer when the code was originally written)? If you could offer some insight, I would be most grateful.

For the sake of completeness, here's how the initializer looks like in this project:

```ruby
if [ 'development', 'staging' ].include? Rails.env
  require 'rack-mini-profiler'
  Rack::MiniProfilerRails.initialize!(Rails.application)
  Rack::MiniProfiler.config.authorization_mode = :whitelist
end
```

And here's the whitelisting (slightly anonymized):

```ruby
before_action do
  if user_logged_in_and_should_see_profiler && [ 'development', 'staging' ].include?(Rails.env)
    Rack::MiniProfiler.authorize_request
  end
end
```

If there's anything else I could provide that would help, I'll be happy to.

**Comment by dgynn** [comment]
Could you see what string is being returned as the `status`? Is it the string "200"?

Could you also print out your middleware stack for staging to see if possibly some other middleware is turning the `status` into a string? You can see your stack with...
```
RAILS_ENV=staging rake middleware
```

**Comment by paweljw** [comment]
Thank you for your prompt response Dave!

I added the following line directly before the comparison in question:
```ruby
puts status.inspect
```

It shows a flurry of "404" strings. The errors are caused here by me skipping precompiling assets locally, but it is indeed the status given as string. It seems that this doesn't happen at all for 200 responses  - maybe for 200 response code the branch containing this comparison is not executed?

Here's the middleware stack dump. I anonymized away the application name at the bottom, for obvious reasons.

```
% RAILS_ENV=staging rake middleware
use Rack::MiniProfiler
use Skylight::Middleware
use Rack::Sendfile
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x000000078c3ca8>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Callbacks
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
use ExceptionNotification::Rack
run Appname::Application.routes
```

While this only happening for 404 (and maybe other non-200 codes - I haven't specifically forced those to happen) is less of an issue, it's still an issue for us - I hope you can appreciate this.

**Comment by SamSaffron** [comment]
I saw rack do this internally so I assume this bad practice is common
enough...

https://github.com/rack/rack/blob/master/lib/rack/content_length.rb#L18

Sure, do a PR to add a .to_i ... if you want to track it down you can
enable the allocation profiler in ruby, then do one request, and then
search for the "200" string and then see who allocated it.

**Comment by paweljw** [comment]
Thank you Sam! I'll try and track down the real culprit. In the meantime, I've opened a pull request for the change we're using internally.
