### ISSUE TITLE
Mongo queries don't show up when PG gem is also loaded

### ISSUE THREAD

**Issue by maxjacobson** [MiniProfiler/rack-mini-profiler#194]
Hello!

Thanks for this wonderful gem.

I saw some possibly related discussion in https://github.com/MiniProfiler/rack-mini-profiler/issues/180, but my issue is a bit different.

In my app, I have both the "pg" gem and the "mongoid" gem loaded. Because of the order of the requires [here](https://github.com/MiniProfiler/rack-mini-profiler/blob/cb7a6cf4d4cd7febb587bcffb4719233034c331b/lib/patches/sql_patches.rb#L49), the PG patch is loaded, and then the Mongo patch is skipped, because rack-mini-profiler doesn't patch more than one db (if I'm understanding this right).

For my app, Mongoid is the main db, and postgres is used in one minor part of the app, so this behavior isn't ideal for me. I've gotten around it for now by lazily requiring PG only in the one file that needs it, but I was a bit confused for a few minutes, and wanted to share the scenario in case it can help inform any decisions about how to specify the preferred patch.

Cheers and thanks again :smile:

**Comment by kbrock** [comment]
Think this is caused by the short circuiting code that determines if a patch is already applied.

**Comment by maxjacobson** [comment]
Yeah, the behavior made sense when I looked at the code. The code seems to make an assumption that there is one ORM per codebase, which is sort of fair, but in our case it's not true. If anything, what I was getting at with this issue is that it might be nice to have a way to specify the preferred ORM for rack-mini-profiler to report on so it doesn't have to guess
