### ISSUE TITLE
Rails 5 `serve_static_assets` deprecation warning

### ISSUE THREAD

**Issue by jayfredlund** [MiniProfiler/rack-mini-profiler#196]
I'm running Rails 5.0.0.beta1.1 and using the master branch of this gem (for Rack 2 support) and running into this message:

```Bash
DEPRECATION WARNING: `serve_static_files` is deprecated and will be removed in Rails 5.1.
Please use `public_file_server.enabled` instead.
 (called from serves_static_assets? at /Users/jay/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rack-mini-profiler-cb7a6cf4d4cd/lib/mini_profiler_rails/railtie.rb:72)
```

The code was committed in https://github.com/MiniProfiler/rack-mini-profiler/commit/ddc193ed77cb3a8db7e44b9a5c404649252fb7af and found in the master branch here: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/mini_profiler_rails/railtie.rb#L68

The deprecation and change is discussed in https://github.com/rails/rails/pull/22173

I'm not sure that adding another `if respond_to?` is a desired solution or what your overall strategy is for supporting multiple versions of Rails going forward, but figured I'd document it here. I can propose something basic, unless someone else is already working on little things like this.

**Comment by xanview** [comment]
Seems this deprecation happens from a few other places also:

```
14:36:15 sidekiq.1 | DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <class:Connection> at /usr/local/lib/ruby/gems/2.3.0/bundler/gems/rack-mini-profiler-a073d1d33a7c/lib/patches/db/mongo.rb:11)
14:36:16 web.1     | DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <class:Connection> at /usr/local/lib/ruby/gems/2.3.0/bundler/gems/rack-mini-profiler-a073d1d33a7c/lib/patches/db/mongo.rb:11)
```

**Comment by kbrock** [comment]
Module prepend was introduced in ruby 2.0.0.

What is the status for supporting 1.9.3 and 1.8.7?

**Comment by jayfredlund** [comment]
Rails 5 requires Ruby 2.2, but ultimately to solve the `alias_method_chain` deprecation while supporting older Rubies, we can probably just check and see if Module responds to prepend and prefer that over `alias_method_chain`. This would be similar to other places in the code, though i question if it's good long-term strategy (which is why I haven't started work on this yet)

**Comment by kbrock** [comment]
yea. I'm just asking how much longer we want to support 1.9.3? If we can drop it, then a switch to prepend would be easier than supporting both mechanisms.

I can't envision a `module_prepend` vs `alias_method_chain` switch like you suggest. `Module.respond_to?(:prepend)` is easy enough. It just seems a like the way the code would be structured for the two would be completely different. But maybe it is simple and I just haven't wrapped my head around it.

**Comment by SamSaffron** [comment]
We can't drop 1.9.3 yet, but we can do a Module.respond_to? ... I am fine with that.

**Comment by jayfredlund** [comment]
:+1:

I'll try and take a look at these this week.

**Comment by SamSaffron** [comment]
Cool, fixed in latest release!
