### ISSUE TITLE
Using ActiveSupport::Notifications

### ISSUE THREAD

**Issue by kbrock** [MiniProfiler/rack-mini-profiler#199]
Sam / all,

Just saw an [rack-profiler](https://github.com/dawanda/rack-profiler) which uses notifications and seems to capture much of what is interesting.

Other than the effort required, are there obvious issues in transitioning across?
(aka - I'm not sure if this is a feature that is much harder than it looks at the surface or if there are parts missing from notifications that prevent transition across)

Thanks,
Keenan

**Comment by SamSaffron** [comment]
I have no objections to adding an option for sipping the notifications
firehose, but there are issues

1. It is less accurate than the current patches (which split time reading
records and time executing sql)
2. It add more overhead than current profiling
3. It is way too noisy to be default on, render 100 partials in a page and
disaster pasta
4. It is less compatible (we work fine without active support)

Open to adding an icon or pp option to enable the notification firehose.

**Comment by kbrock** [comment]
@SamSaffron thanks you for your insight

I was having trouble getting the SQL tracing working with a rails 3.2 version of our app. So I had thought just tapping into notifications would be simpler and more compatible. Less monkey patching.

I guess I had thought it would be less overhead since these events are already generated by sql and mongo / others. And easier to migrate.

I'll take your input into account and think this through a little more

**Comment by kbrock** [comment]
closing this issue - will use PR to focus on the conversation
