### ISSUE TITLE
NoMethodError: private method `singleton_class' called for Rack::MiniProfiler:Class

### ISSUE THREAD

**Issue by mockdeep** [MiniProfiler/rack-mini-profiler#215]
We have a stub in our specs just to test that the profiler gets enabled and with the recent upgrade we saw the spec start breaking:

```
     NoMethodError:
       private method `singleton_class' called for Rack::MiniProfiler:Class
````

The spec looks like:

```ruby
expect(Rack::MiniProfiler).to receive(:authorize_request)

get(:index)
```

**Comment by SamSaffron** [comment]
jeez i hate stubs :) care to try a PR to fix it?

**Comment by seanlinsley** [comment]
Perhaps adding `and_call_original` to the stub would fix it. Unless you're trying to disable authentication?

If you are trying to disable authentication, it seems like the better option is to actually disable it as part of your test environment setup.

**Comment by mockdeep** [comment]
We're just trying to verify that it gets called. I don't think adding `and_call_original` would do the trick in this case, since rspec stubs out the method either way. The `singleton_class` method was made private in a recent commit on `rack-mini-profiler`, which is a method rspec uses for stubbing. I'll see if I can get a fix in, unless somebody else wants to tackle it.

**Comment by seanlinsley** [comment]
That being: #190.

@SamSaffron why not drop support for Ruby 1.9? [Ruby 2.0 is no longer supported](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/). For those still on older versions, they wouldn't be upgrading gems for the same reasons they aren't upgrading Ruby.

Or actually, [`singleton_class` is available as early as 1.9.3](http://ruby-doc.org/core-1.9.3/Object.html#method-i-singleton_class) so we don't need to drop support for Ruby versions just for this change.

**Comment by seanlinsley** [comment]
There is [this in the gemspect](https://github.com/MiniProfiler/rack-mini-profiler/blob/77b2c67105278e3eada60da942b8f2aabca36bec/rack-mini-profiler.gemspec#L22) for Ruby 1.8, but Travis isn't actually running 1.8. I assume 1.8 is no longer supported?

**Comment by SamSaffron** [comment]
Yes ... 1.8 is not longer supported

**Comment by davebrace** [comment]
I ran into the same thing after upgrading. Good point about not needing to stub. I updated our specs to just use `Rack::MiniProfiler.request_authorized?` to check after the request if it was authorized or not.

For the example above you could do this: 

```ruby
get(:index)

expect(Rack::MiniProfiler.request_authorized?).to eq true
```

**Comment by mockdeep** [comment]
Good call. We had switched to checking `Thread.current[:mp_authorized]`, which felt really dirty.

**Comment by SamSaffron** [comment]
ok I am closing this, I see not point carrying any extra code to support rspec weird stubbing here

- make a req as admin in production mode
- check that stuff is authorized

- make a req a normal user in production mod
- check that stuff is not authorized 

You can do all of this testing by injecting middleware in position 0 that checks stuff on env or invokes MP. 

Checking the internal implementation of MP in a spec is not something I support ... supporting :)
