### ISSUE TITLE
Interested in DynamoDB Store

### ISSUE THREAD

**Issue by mattzollinhofer** [MiniProfiler/rack-mini-profiler#216]
I'm thinking about writing a store for dynamo db, any interest in a PR to add support for it?

**Comment by SamSaffron** [comment]
Sure, go for it!

**Comment by mattzollinhofer** [comment]
After looking into this more, I don't really think DynamoDB is a great fit as a store for rack-mini-profiler. The lack of auto expiration makes managing the entries a bit cumbersome. Seemed like a good idea at the time...

If enough people express interest for Dynamo support I could probably be convinced to pick it back up again.
