### ISSUE TITLE
RSpec 3

### ISSUE THREAD

**Issue by seanlinsley** [MiniProfiler/rack-mini-profiler#219]
As I discovered in #215 / #217, we're still using RSpec 2. The big change is a syntactic one:

``` ruby
# RSpec 2
author.name.should == 'Julie'

# RSpec 3
expect(author.name).to eq 'Julie'
```

While the new syntax is more to read and more to type, I feel that it's better because it means RSpec embeds less methods onto all objects.

@SamSaffron what do you think? I don't want to go to the trouble of creating a PR for this if you prefer the old syntax.

**Comment by SamSaffron** [comment]
Honestly I would be happy porting it to minitest :) sure, fine to update
syntax to rspec expect everywhere.

**Comment by kbrock** [comment]
Interesting, minitest uses `_(value)` vs rspec's `expect(value)` - looks like everyone is going away from the `Object` monkey patching. so seems like a good direction.

FYI, [transpec](https://github.com/yujinakayama/transpec) auto converts rspec tests

**Comment by SamSaffron** [comment]
whoever wants to upgrade rspec here, be my guest
