### ISSUE TITLE
Small documentation issue for flamegraph_sample_rate configuration

### ISSUE THREAD

**Issue by dnasseri** [MiniProfiler/rack-mini-profiler#222]
The configuration documentation in the readme file is a bit confusing for flamegraph_sample_rate configuration. The configuration documentation makes it look like it accepts a string in the form of '0.1ms' as opposed to a float 0.1.

**Comment by dnasseri** [comment]
PR here: https://github.com/MiniProfiler/rack-mini-profiler/pull/221

**Comment by kbrock** [comment]
@dnasseri thanks. Is this issue all set to close?

**Comment by dnasseri** [comment]
@kbrock for sure, thanks!
