### ISSUE TITLE
Profiler doesn't display on Turbolinks 5 page loads

### ISSUE THREAD

**Issue by cannikin** [MiniProfiler/rack-mini-profiler#224]
I opened a similar issue over at the Turbolinks repo: https://github.com/turbolinks/turbolinks/issues/53

To be clear this only seems to be an issue with the new Turbolinks 5 stuff, loaded via `gem 'turbolinks', '~> 5.0.0.beta'`

Everything displays fine on full page loads (hitting ENTER in the URL bar, or reloading) but on Turbolinks-loaded pages the profiler never shows.

If you navigate a few pages, then do a full page load, the profiler will show an "x 4" or similar letting you know there were four total pages that were captured since the last time you saw it and then you can expand it to see details for each page, but ideally it should show the profiler on every load of course.

I'm not sure if the solution is just drop a `data-turbolinks` attribute into the JS that mini-profiler is appending before the closing body tag, or if the mini-profiler JS itself needs to change. Any ideas?

**Comment by nateberkopec** [comment]
Pretty sure this is related to https://github.com/turbolinks/turbolinks/issues/9.

**Comment by cannikin** [comment]
Ahhh, I bet that's it. The event name here will need to be changed: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/html/includes.js#L407 (to `turbolinks:load`, perhaps?) but until Turbolinks is re-executing JS on page load it won't make much difference! Feel free to close unless you want to keep this as a reminder to change that event name when the time comes. :)

**Comment by kobaltz** [comment]
I was able to fix my mini-profiler by using the compatibility js  snippet in the turbolinks beta and switching my storage to redis. My mini-profiler initializer looks like this now.

    unless Rails.env.production?
      Rack::MiniProfiler.config.storage_options = { host: Rails.application.secrets.redis_server, port: Rails.application.secrets.redis_port }
      Rack::MiniProfiler.config.storage = Rack::MiniProfiler::RedisStore
      Rack::MiniProfiler.config.disable_caching = false
    end

**Comment by tirdadc** [comment]
This doesn't seem to be fixed now that we have Rails 5.

**Comment by tirdadc** [comment]
<a href='https://github.com/turbolinks/turbolinks#working-with-script-elements'>Script element support</a> was added in Turbolinks 5.0.0.beta4, is there any way we could get a release that accounts for that?

**Comment by janklimo** [comment]
Is this still an issue? We're using Turbolinks 5.2.0 with Rails 5.2.3 and profiler shows up on every page visit.

**Comment by jonathanhefner** [comment]
I believe this has been fixed by #275.

**Comment by SamSaffron** [comment]
Yeah I think this is good now, @cannikin  let me know if you are still seeing any issues here.
