### ISSUE TITLE
Update to 0.9.9.x crashes server

### ISSUE THREAD

**Issue by cavpollo** [MiniProfiler/rack-mini-profiler#240]
Recently I updated a project's gemfile and when starting the server it crashed:

    /home/cavpollo/.rvm/gems/ruby-2.1.3/gems/rack-mini-profiler-0.9.9/lib/patches/db/mongo.rb:2:in `<top (required)>': uninitialized constant Mongo::Server (NameError)
	from /home/cavpollo/.rvm/gems/ruby-2.1.3/gems/rack-mini-profiler-0.9.9/lib/patches/sql_patches.rb:49:in `<top (required)>'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3/gems/rack-mini-profiler-0.9.9/lib/rack-mini-profiler.rb:30:in `<top (required)>'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:76:in `require'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:72:in `each'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:72:in `block in require'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:61:in `each'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:61:in `require'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3@global/gems/bundler-1.7.3/lib/bundler.rb:133:in `require'
	from /home/cavpollo/my_project/config/application.rb:13:in `<top (required)>'
	from /home/cavpollo/my_project/config/environment.rb:2:in `require'
	from /home/cavpollo/my_project/config/environment.rb:2:in `<top (required)>'
	from config.ru:4:in `require'
	from config.ru:4:in `block in <main>'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_eval'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `eval'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `block in builder'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:752:in `call'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:752:in `build_app!'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:129:in `start'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3/bin/unicorn:23:in `load'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3/bin/unicorn:23:in `<main>'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/cavpollo/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
    exited with code 1

After some debugging, I concluded that updating my rack-mini-profiler version from 0.9.7 to version 0.9.9 and up made the app crash (yes, I tested version 0.9.9.1 and .2 as well). 
It seems that **version 0.9.8 runs just fine**.

Any ideas of why would this be happening?

Specs:
- ruby 2.1.3
- rails 3.2.22
- foreman (0.81.0)
- mongo (1.12.5)
- mongodb_logger (0.6.2)
- unicorn (5.1.0)

**Comment by kbrock** [comment]
Hello @cavpollo rack-mini-profiler supports mongo v 2.0 and above.

I've put in a patch that will not puke on this version of mongo, but you won't get database monitoring.
Not sure exactly when the mongo was switched from 1.x to 2.x

**Comment by cavpollo** [comment]
ok, thanks =)
