### ISSUE TITLE
Rails5 and Deflate middleware

### ISSUE THREAD

**Issue by dreyks** [MiniProfiler/rack-mini-profiler#242]
So I've been migrating an app to Rails5 and rack mini profiler just stopped showing up.
The 

``` ruby
require 'rack-mini-profiler'

Rack::MiniProfilerRails.initialize!(Rails.application)

Rails.application.middleware.delete(Rack::MiniProfiler)
Rails.application.middleware.insert_after(Rack::Deflater, Rack::MiniProfiler)
```

does not work anymore, due to [this commit](https://github.com/rails/rails/commit/a39498ae060f07132ddbbc45933a819686f0eb24) in rails. Now the `delete` operations are issued at the end

**Comment by dreyks** [comment]
Ok, this, though being ugly, works

```ruby
Rails.application.middleware.swap(Rack::Deflater, Rack::MiniProfiler)
Rails.application.middleware.swap(Rack::MiniProfiler, Rack::Deflater)
```

**Comment by seanlinsley** [comment]
@dreyks could you open a PR to update the readme?

**Comment by dreyks** [comment]
#258 seems to fix this. I'll test it and close the issue

**Comment by ChallahuAkbar** [comment]
So, was this fixed then?

**Comment by OsamaSayegh** [comment]
Yes this was fixed thanks to https://github.com/MiniProfiler/rack-mini-profiler/pull/258. I'm closing this issue but feel free to open a new one if you still see this. Thanks!
