### ISSUE TITLE
Extending Profile with Memory

### ISSUE THREAD

**Issue by sb8244** [MiniProfiler/rack-mini-profiler#246]
Hi Sam, what do you think about inserting https://github.com/SamSaffron/memory_profiler as an option like `pp=memoryprofile`. This would be consistent with flamegraphs and would show the output of the memory profiling tool.

I'd be happy to PR this if you would consider it.

**Comment by dgynn** [comment]
Good news! That already exists but isn't documented. Use `pp=profile-memory`. 

You can see the implementation and possible params here:
https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/mini_profiler/profiler.rb#L202

**Comment by seanlinsley** [comment]
It would be really useful to document the available options, if anyone has the time.

**Comment by SamSaffron** [comment]
There is a little "help" link that takes you to pp=help ... though I
totally support improving the readme!

**Comment by sb8244** [comment]
I actually am not using the in-page extension, so a readme update would be great.

I would be happy to put that together!

**Comment by SamSaffron** [comment]
Sure go for it!

**Comment by dgynn** [comment]
@sb8244 Thanks for updating the readme.

For the `memory_profiler_allow_files` and `memory_profiler_ignore_files` arguments those parameters will get converted into Regexp in memory_profiler.
So you can do things like... `&memory_profiler_allow_files=active_record|app` (with a pipe character) to "or" the values.
