### ISSUE TITLE
ActionController::InvalidCrossOriginRequest on production

### ISSUE THREAD

**Issue by danielschwartz** [MiniProfiler/rack-mini-profiler#259]
Hi,

I'm getting a `ActionController::InvalidCrossOriginRequest` exception being raised when trying to view `Rack::MiniProfiler` on production. It only occurs for the action requesting the mini profiler stuff. The error printed in my logs is:

```
Security warning: an embedded <script> tag on another site requested protected JavaScript. If you know what you're doing, go ahead and disable forgery protection on this action to permit cross-origin JavaScript embedding.
```

The actual code being returned by rails is `422 Unprocessable Entity`

I'd love to get this working on production so I can track down some slow stuff only happening on my production servers. Any help would be appreciated!

**Comment by nateberkopec** [comment]
I just looked at this for a minute and TBH I don't really get it. Sam is clearly doing it somehow on Discourse but his config doesn't have anything that clearly addresses this. 

I also don't understand why Rails is letting almost identical requests to other static JS on my page go through, but this doesn't.

**Comment by SamSaffron** [comment]
Looks like a CSP to me... what CSP do you have defined?

**Comment by keshavbiswa** [comment]
I would like to help maintain this project. This seems like a CSP problem can we close this? @nate-at-gusto
