### ISSUE TITLE
authorize_request is ignored, mini-profiler runs all the time

### ISSUE THREAD

**Issue by kshnurov** [MiniProfiler/rack-mini-profiler#260]
After updating from 0.9.8 to 0.10.1 on 2 different projects mini-profiler gets called on every request in production:
![2016-07-25 19 50 09](https://cloud.githubusercontent.com/assets/498185/17109549/111ddbd8-52a1-11e6-9661-d8c0596eac2d.png)
I'm using `Rack::MiniProfiler.authorize_request if Rails.env.development?`, so it shouldn't run at all.

**Comment by SamSaffron** [comment]
Do you have a repro in a clean env, we have this code that takes care of it:

https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/mini_profiler_rails/railtie.rb#L35-L37

**Comment by kshnurov** [comment]
@SamSaffron no, I don't.
What does `authorization_mode = :whitelist` means? There's no docs at all.
However, this part of railtie didn't changed since 0.9.8.

**Comment by thesecretmaster** [comment]
@kshnurov If you're not in a production environment, miniprofiler will run on every page by default, and so `authorize_request` won't do anything. As per [this section in the readme](https://github.com/MiniProfiler/rack-mini-profiler#access-control-in-non-development-environments), you'll need to set the configuration option `Rack::MiniProfiler.config.authorization_mode = :whitelist`.

**Comment by SamSaffron** [comment]
I added some clarification here 

https://github.com/MiniProfiler/rack-mini-profiler/blob/5d0618e5a1c69ff39510806d2742607078cd0efa/README.md#L161-L196
