### ISSUE TITLE
Position bottom (left/right)?

### ISSUE THREAD

**Issue by mrkongo** [MiniProfiler/rack-mini-profiler#262]
Maybe is necessary another config option for bottom positioning?

**Comment by SamSaffron** [comment]
sure, feel free to submit a PR for custom positioning

**Comment by rafaelbiriba** [comment]
Waiting for review and approval 😄 
Please do it as soon as possible, since I need to use this gem in "bottom" position.
Thanks 🙏

**Comment by rafaelbiriba** [comment]
@SamSaffron you can close this ticket!

**Comment by SamSaffron** [comment]
thanks 👍
