### ISSUE TITLE
ERROR Encoding::UndefinedConversionError: "\xD0" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by Elsopuro** [MiniProfiler/rack-mini-profiler#263]
ERROR Encoding::UndefinedConversionError: "\xD0" from ASCII-8BIT to UTF-8
/.rvm/gems/ruby-2.2-head/gems/json-1.8.3/lib/json/common.rb:223:in `encode'
/.rvm/gems/ruby-2.2-head/gems/json-1.8.3/lib/json/common.rb:223:in`generate'
/.rvm/gems/ruby-2.2-head/gems/json-1.8.3/lib/json/common.rb:223:in `generate'
/.rvm/gems/ruby-2.2-head/gems/rack-mini-profiler-0.10.1/lib/mini_profiler/timer_struct/base.rb:27:in`to_json'
/.rvm/gems/ruby-2.2-head/gems/json-1.8.3/lib/json/common.rb:223:in `generate'
/.rvm/gems/ruby-2.2-head/gems/json-1.8.3/lib/json/common.rb:223:in`generate'
/.rvm/gems/ruby-2.2-head/gems/rack-mini-profiler-0.10.1/lib/mini_profiler/timer_struct/base.rb:27:in `to_json'
/.rvm/gems/ruby-2.2-head/gems/json-1.8.3/lib/json/common.rb:223:in`generate'
/.rvm/gems/ruby-2.2-head/gems/json-1.8.3/lib/json/common.rb:223:in `generate'
/.rvm/gems/ruby-2.2-head/gems/rack-mini-profiler-0.10.1/lib/mini_profiler/timer_struct/base.rb:27:in`to_json'
/.rvm/gems/ruby-2.2-head/gems/json-1.8.3/lib/json/common.rb:223:in `generate'
/.rvm/gems/ruby-2.2-head/gems/json-1.8.3/lib/json/common.rb:223:in`generate'
/.rvm/gems/ruby-2.2-head/gems/rack-mini-profiler-0.10.1/lib/mini_profiler/timer_struct/base.rb:27:in `to_json'
/.rvm/gems/ruby-2.2-head/gems/json-1.8.3/lib/json/common.rb:223:in`generate'
/.rvm/gems/ruby-2.2-head/gems/json-1.8.3/lib/json/common.rb:223:in `generate'
/.rvm/gems/ruby-2.2-head/gems/rack-mini-profiler-0.10.1/lib/mini_profiler/timer_struct/page.rb:65:in`to_json'
/.rvm/gems/ruby-2.2-head/gems/rack-mini-profiler-0.10.1/lib/mini_profiler/profiler.rb:102:in `serve_results'
/.rvm/gems/ruby-2.2-head/gems/rack-mini-profiler-0.10.1/lib/mini_profiler/profiler.rb:126:in`serve_html'
/.rvm/gems/ruby-2.2-head/gems/rack-mini-profiler-0.10.1/lib/mini_profiler/profiler.rb:175:in `call'
/.rvm/gems/ruby-2.2-head/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in`call'
/.rvm/gems/ruby-2.2-head/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
/.rvm/gems/ruby-2.2-head/gems/rack-1.6.4/lib/rack/lock.rb:17:in`call'
/.rvm/gems/ruby-2.2-head/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/.rvm/gems/ruby-2.2-head/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in`service'
/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/webrick/httpserver.rb:94:in`run'
/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

**Comment by AndreiMotinga** [comment]
+1

**Comment by SamSaffron** [comment]
something needs some scrub love

**Comment by fruwe** [comment]
+1

**Comment by antoniosb** [comment]
:+1

**Comment by antoniosb** [comment]
I managed to fix this issue by removing the ```to_json``` method at ``` lib/mini_profiler/timer_struct/base.rb```. 

I'm upgrading a Rails app from 3.2 all the way to 5. (currently at 4.1). By reading [this issue](https://github.com/rails/rails/issues/15226) and [this pull request](https://github.com/rails/rails/pull/12183) I managed to install [the extracted encoder](https://github.com/rails/activesupport-json_encoder) and then this method wasn't necessary anymore.

Currently at Ruby 2.3.1 and Rails 4.1
