### ISSUE TITLE
Undefined method sleepy_run for #<Rack::MiniProfiler::MemoryStore:0x007facd21ad548>

### ISSUE THREAD

**Issue by backus** [MiniProfiler/rack-mini-profiler#265]
This seems to be an issue on master but not in the latest release. Reproduce with:

``` ruby
# Gemfile
source 'https://rubygems.org'

gem 'rack', '2.0.1'
gem 'rack-mini-profiler', github: 'MiniProfiler/rack-mini-profiler'
```

**config.ru**:

``` ruby
# Make exceptions in other threads visible
require 'thread'
Thread.abort_on_exception = true

require 'rack'
require 'rack-mini-profiler'

app = Rack::Builder.new do
  use Rack::MiniProfiler

  run ->(_) do
    [
      200,
      { 'Content-Type' => 'text/html' },
      ['<html><body>Hello!</body></html>']
    ]
  end
end

Rack::Server.start(app: app)
```

Note the `Thread.abort_on_exception`. This makes the error visible (but doesn't crash the server) using a normal rackup server. The application I encountered this on uses puma and actually crashes on boot due to this issue but I couldn't get a quick minimal reproduction with puma.

**Comment by burlesona** [comment]
Seeing the same thing on rack-mini-profiler (0.10.5)

**Comment by olivervbk** [comment]
I fixed this in my PR:
https://github.com/MiniProfiler/rack-mini-profiler/pull/310

**Comment by rvalenciano** [comment]
Any progress on this? Any help needed? @SamSaffron @olivervbk

**Comment by SamSaffron** [comment]
Just merged a pr by @olivervbk to fix it!

**Comment by rvalenciano** [comment]
Thx @SamSaffron
