### ISSUE TITLE
Rack::MiniProfiler.step documented?

### ISSUE THREAD

**Issue by ReContextDataSolutions** [MiniProfiler/rack-mini-profiler#274]
Hello,

I just started using rack-mini-profiler this week. Great gem, thanks!

When reading the blog post (https://samsaffron.com/archive/2012/07/12/miniprofiler-ruby-edition) I saw this method being used: Rack::MiniProfiler.step(name, &blk), but couldn't find any mention about it on the README here on the repo. Is there any special reason why it is undocumented? Should I submit a PR?

Thanks!

**Comment by SamSaffron** [comment]
no reason at all, feel free to submit a PR!

**Comment by kbrock** [comment]
@ReContextDataSolutions I think `profile_method` does what you want:

In an `config/initializers/mini_profiler.rb` I have mini profiler configs and a few `step` points.
```ruby
    [
      "Module::Class1.method",
      "Module::Class1#method2",
    ].each do |method_desc|
      klass_name, mode, method_name = method_desc.split(/([.#])/)
      klass = klass_name.safe_constantize

      begin
        if klass && mode == "."
          ::Rack::MiniProfiler.profile_singleton_method(klass, method_name) { |a| method_desc }
        elsif klass
          ::Rack::MiniProfiler.profile_method(klass, method_name) { |a| method_desc }
        else
          puts "Can not find class: #{klass} (#{method_desc})"
        end
      rescue
        puts "Can not bind: #{method_desc}"
      end
    end
```
