### ISSUE TITLE
Environment Variables in Log?

### ISSUE THREAD

**Issue by reinierbutot** [MiniProfiler/rack-mini-profiler#280]
Hi, I was wondering what the reason was behind the decision to include all environment variables in the log? Because I don't see the need.

This is an issue. Because this could lead to the indexation of a page filled with all passwords and keys of a site, by search engines. Especially when users of this gem are having issues with authorization.

**Comment by SamSaffron** [comment]
It eases diagnostics but I completely support making it optional, default off. (I thought we already had a setting, so we can simply flip it, PR welcome)  

However if you are running with broken auth in production you are in for a very bad time.

**Comment by SamSaffron** [comment]
Note if you want to avoid any risk here, be sure to use `disable_env_dump` per readme.
