### ISSUE TITLE
PG::Connection#async_exec using exec?

### ISSUE THREAD

**Issue by scottbartell** [MiniProfiler/rack-mini-profiler#282]
It looks like `async_exec` is calling `exec_without_profiling` rather than `async_exec_without_profiling`, is there a reason for this?

https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/patches/db/pg.rb#L90

**Comment by SamSaffron** [comment]
afaik exec and exec_async are aliases in latest pg

**Comment by rickmzp** [comment]
Hi @SamSaffron,

I looked at the PG source code, and it seems that `exec` and `exec_async` are implemented differently.

See `exec`:
 - https://github.com/ged/ruby-pg/blob/master/ext/pg_connection.c#L3983
 - https://github.com/ged/ruby-pg/blob/master/ext/pg_connection.c#L952

See `async_exec`:
 - https://github.com/ged/ruby-pg/blob/master/ext/pg_connection.c#L4048
 - https://github.com/ged/ruby-pg/blob/master/ext/pg_connection.c#L3181

Best,
Rick

**Comment by SamSaffron** [comment]
I see:

someone changed their minds here:

v0.17.1 [2013-12-18] Michael Granger <ged@FaerieMUD.org>

Bugfixes:

   -

   Fix compatibility with signal handlers defined in Ruby. This reverts
   cancelation of queries running on top of the blocking libpq API (like
   Connection#exec) in case of signals. As an alternative the #async_exec can
   be used, which is reverted to use the non-blocking API, again.
   -

   Wrap PQcancel to be called without GVL. It internally waits for the
   canceling connection.

Documentation fixes:

   -

   Fix documentation for PG::Connection::conndefaults.


Sure ... a PR to correct this is welcome.
