### ISSUE TITLE
Instructions for Custom middleware ordering doesn't work properly on rails 5

### ISSUE THREAD

**Issue by PikachuEXE** [MiniProfiler/rack-mini-profiler#283]
Source:
https://github.com/MiniProfiler/rack-mini-profiler#custom-middleware-ordering-required-if-using-rackdeflate-with-rails

Using 
- rails 5.0.1
- rack-mini-profiler 0.10.2

1. If I put `require: false` this error will be thrown:
```
rack-mini-profiler-0.10.2/lib/mini_profiler_rails/railtie.rb:93:in `>': comparison of Fixnum with nil failed (ArgumentError)
```

2. If `require: false` is removed, this error is thrown instead:
```
MiniProfilerRails initialized twice. Set `require: false' for rack-mini-profiler in your Gemfile (RuntimeError)
```

3. if `Rack::MiniProfilerRails.initialize!(Rails.application)` is removed, the error in (1) is thrown again

Let me know if you need more info

**Comment by martinandert** [comment]
This is actually a Rails 5 issue. https://github.com/rails/rails/issues/26303#issuecomment-261147590 has a workaround.

**Comment by troystarwalt** [comment]
This is a bit of a follow up on the steps referenced in @martinandert 's link.

After working through it, I'm receiving an error on compiling assets in production:

`No such middleware to insert before: ActionDispatch::Static`

Below is how I've setup files.

I created an initializer file: `rack-mini-profiler.rb`
```
require rack-mini-profiler

Rack::MiniProfilerRails.initialize!(Rails.application)
# #
Rails.application.middleware.swap(Rack::MiniProfiler, nil)
Rails.application.middleware.delete(nil)
Rails.application.middleware.insert_after(Rack::Deflater, Rack::MiniProfiler)

```

`application.rb`
```
require_relative 'boot'

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module InternalSite
  class Application < Rails::Application
    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.
    config.exceptions_app = self.routes
    config.middleware.use Rack::Deflater
    config.font_assets.origin = "*"
  end
end
```

**Comment by davidrunger** [comment]
Below is the solution that works for me (using Rails `master` (currently at this commit: https://github.com/rails/rails/commit/b1f6d8c8d8ad3e2e5b96e95b455c70f2c895ce14)).

Instead of the suggested approach of:
```rb
# config/initializers/rack_profiler.rb
Rails.application.middleware.delete(Rack::MiniProfiler)
Rails.application.middleware.insert_after(Rack::Deflater, Rack::MiniProfiler)
```

I did this:
```rb
# config/initializers/rack_profiler.rb
Rails.configuration.middleware.move_after(Rack::Deflater, Rack::MiniProfiler)
```

The `#move_after` method that I am using was added here: https://github.com/rails/rails/pull/38169 . (Unfortunately, I don't think that change is yet included in any released version of `rails`. I guess that change will maybe be included in Rails 6.1.0, whenever that is released?)

**Comment by SamSaffron** [comment]
We got to update the readme here @davidrunger  can you maybe give it a shot.

The general approach imo for custom init would be to `require: false` mini profiler and then require it in an intializer like so: 

https://github.com/discourse/discourse/blob/a2d939608d5b3adc7f037dc0ca38e7d1f6b895f6/config/initializers/006-mini_profiler.rb#L14-L15

No need to fight then with the middleware stack.

**Comment by OsamaSayegh** [comment]
There is no need to reorder middlewares anymore because MP now tells `Rack::Deflater` not to compress **profiled** requests if `Rack::Deflater` is inserted after MP in the middleware stack. We've also removed the instructions for middleware reordering from README.
