### ISSUE TITLE
Problem with authorization mode == :whitelist

### ISSUE THREAD

**Issue by justin808** [MiniProfiler/rack-mini-profiler#286]
On the 3rd line of the `def call(env)` method in profiler.rb: 

      MiniProfiler.deauthorize_request if @config.authorization_mode == :whitelist

If I have my application controller authorize the request for the admin user, this line wipes out that authorization.

Thus, with production mode and the whitelist authorization, rack-mini-profiler never shows.

**Comment by SamSaffron** [comment]
this is not the case really, the flow in whitelist mode is

- We deauthorize the request
- You call `Rack::MiniProfiler.authorize_request` somewhere in your controller
- Request is authorized
