### ISSUE TITLE
jQuery bind() is deprecated as of version 3

### ISSUE THREAD

**Issue by blimmer** [MiniProfiler/rack-mini-profiler#287]
I'm working on migrating my app over to jQuery 3 and noticed this when using the migration helper ([info on migration helper](https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/) / [info on bind deprecation](http://api.jquery.com/bind/))

![screen shot 2017-03-16 at 10 16 55 am](https://cloud.githubusercontent.com/assets/630449/24006533/b7eb61d6-0a31-11e7-8239-54d883261606.png)

Depending on this project's stated jQuery support (if 1.7+), I think these methods can be replaced the `on` handler.

https://github.com/MiniProfiler/rack-mini-profiler/blob/a29713031ce88845b9b468ba1c229972f61b423f/lib/html/includes.js#L369

**Comment by SamSaffron** [comment]
ok, fixed in latest, thanks
