### ISSUE TITLE
Log bindings for pg prepared statements

### ISSUE THREAD

**Issue by antonbaron** [MiniProfiler/rack-mini-profiler#288]
Hi everyone, thx for great gem! 
Anyone knows how to show prepared sql bindings in profiler results?
E.g. show 
`SELECT  "foo".* FROM "foo" WHERE "foo"."bar" = $1 LIMIT $2  [["bar", "baz"], ["LIMIT", 1]]`
instead of just
`SELECT  "foo".* FROM "foo" WHERE "foo"."bar" = $1 LIMIT $2`

Imho it's very important information to show in profiler

**Comment by SamSaffron** [comment]
there is an element of risk there cause the params can be enormous in some cases, I am totally open for a PR that adds this support optionally.

**Comment by antonbaron** [comment]
Ok, we could add a config key "maximum prepared statement param length" to deal with it. 
As far as I understand we can use something like https://github.com/MiniProfiler/rack-mini-profiler/issues/171 . I'll git into this, thx for a reply.

**Comment by kbrock** [comment]
We have [sql_max_param_length](https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/mini_profiler/config.rb#L21)

Thought that was used, is passed into the back end, and has specs too.
The only missing part is the modifications to serialization to the front end and the javascript to render it.

(I use a custom ruby back end script, and am viewing binding variables just find)

**Comment by SamSaffron** [comment]
Nice, totally support fixing this!

**Comment by SamSaffron** [comment]
completed and merged now
