### ISSUE TITLE
How to not include javascript in AMP pages

### ISSUE THREAD

**Issue by feliperaul** [MiniProfiler/rack-mini-profiler#296]
I couldn't find any setting to exclude the JS include in specific pages. We need to avoid inserting miniprofiler javascript (regardless of env) in google's AMP pages, because it breaks validation. Thanks in advance!

**Comment by SamSaffron** [comment]
This question does not make much sense to me, you would be in whitelist mode in production, all anon requests (including the one's AMP is pulling into its CDN) would not include any resources.
