### ISSUE TITLE
Badge disappearing on production

### ISSUE THREAD

**Issue by reneklacan** [MiniProfiler/rack-mini-profiler#297]
Looks like badge disappears when counter goes over 20.

I am using rack-mini-profiler (0.10.5) and rails (5.1.1). And I use Redis storage.

Short recording of what happens after refresh:
![](http://g.recordit.co/Wp3EPMv0HY.gif)

If I am quick enough to click it before it reaches 20 it stays there. Works as expected on pages where counter is 20 or less.

**Comment by reneklacan** [comment]
I just noticed `max_traces_to_show` in config options. Ignore me, I'm retarded.

**Comment by SamSaffron** [comment]
I do agree the behavior is somewhat surprising, I think it should just get
stuck at 20 if this is the case or something along those lines.
