### ISSUE TITLE
Mini profiler disappears

### ISSUE THREAD

**Issue by yefim** [MiniProfiler/rack-mini-profiler#300]
It seems to disappear after an AJAX request goes through. Here's a video of it happening: https://streamable.com/18dbt

**Comment by SamSaffron** [comment]
This is by design, but I think the design is kind of silly.

We only keep miniprofiler around for 20 reqs, it vanishes after that
(configurable)

What is happening is on click you are flooding your server with 20 reqs.

On Mon, Jun 12, 2017 at 3:03 PM, Yefim Vedernikoff <notifications@github.com

**Comment by yefim** [comment]
@SamSaffron thanks for the quick response! It worked :)

**Comment by technicalpickles** [comment]
For reference, the setting is `max_traces_to_show`
