### ISSUE TITLE
Railtie prevents any type of storage other than file storage

### ISSUE THREAD

**Issue by willtcarey** [MiniProfiler/rack-mini-profiler#301]
The railtie as it's set up forces you to use the FileStore storage option due to [this line](https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/mini_profiler_rails/railtie.rb#L44).

This makes it impossible to follow any of the directions from the readme around changing your storage option and it had me scratching my head for a long time 😀
So what I'm seeing is that you're not able to change the storage beforehand because the railtie will overwrite whatever storage option you see and you're not able to change the storage after the profiler is initialized because it stores an instance of the storage class at the time of initialization so you wind up being stuck!

I'm not sure the best way to resolve this. You have a comment in the railtie about the file store being better than the default memory store so maybe it would work to change the default from the memory store to the file store? I'm open to any suggestions on a way to resolve this.

Currently I just copied the contents of the railtie initializer to my local project and took out the part where it assigns the file store so I'm working for now but it would be great if we could fix this so other people aren't confused.

Thanks

**Comment by SamSaffron** [comment]
Hmm ... we better fix this, care to try to patch it so the instructions in the readme work?

**Comment by willtcarey** [comment]
@SamSaffron Sure, check out #302
