### ISSUE TITLE
Issue with badge vertical position options

### ISSUE THREAD

**Issue by adamlofting** [MiniProfiler/rack-mini-profiler#314]
I've just setup MiniProfiler on an app but ran into an issue using the suggested config in the README ([here](https://github.com/MiniProfiler/rack-mini-profiler#configuration-options)).

Aligning the badge to the right _does_ work for me.
```
Rack::MiniProfiler.config.position = 'right'
```

But neither of these vertical alignment options work for me:
```
Rack::MiniProfiler.config.position = 'bottom-right'
Rack::MiniProfiler.config.position = 'bottom-left'
```

For both of those config options, the badge ends up in the default location in the top left of the page.

I took a quick look around the codebase to see if I could find an obvious fix, but didn't spot anything so I hope you don't mind me filing this as a ticket. 

Thanks - the rest of this is working great - and it's a really useful tool. 👍

**Comment by pashamur** [comment]
Are you using version 0.10.5 of the gem? The support for bottom/top parameters is in master, but it hasn't been rolled into a version release yet as far as I know (I ended up forking the repo since I needed bottom/top support). I think we could ping @SamSaffron to do a version bump.

**Comment by adamlofting** [comment]
Aha, yes. That would explain it. 👍 

I'm running `0.10.5` and was looking at the docs in `master`.

**Comment by SamSaffron** [comment]
I pushed 0.10.6, let me know if it is working for you!

Also added some help we needed into the readme :)
