### ISSUE TITLE
Rake task not found?

### ISSUE THREAD

**Issue by askl56** [MiniProfiler/rack-mini-profiler#317]
Hey,

After gem install, I get

```
Could not find generator rack_profiler:install.

```

A cursory check of `rake -T` confirms this. Has this problem happened for anyone else?

**Comment by askl56** [comment]
Bump

**Comment by SamSaffron** [comment]
I just did a new release, can you try on latest

**Comment by askl56** [comment]
No joy :(

**Comment by SamSaffron** [comment]
assuming this is fixed on latest... closing
