### ISSUE TITLE
Random 404 errors in /mini-profiler-resources

### ISSUE THREAD

**Issue by shreve** [MiniProfiler/rack-mini-profiler#321]
rails v4.2.8
rack-mini-profiler v0.10.6

I'm getting randomly distributed 404 errors of mini profiler assets between page loads.
On some pages `/mini-profiler-resources/includes.js` is missing, on others, that and `/mini-profiler-resources/includes.css` is gone too.

**Comment by symmetriq** [comment]
Same problem here. Among other things, it interrupts our JS test suite (Teaspoon) and causes it to redirect to the login page (because we handle 404s as unauthorized requests).

**Comment by SamSaffron** [comment]
I am going to need a repro here, how is this deployed in production?

**Comment by shreve** [comment]
@SamSaffron I'll try to repro in a new rails app. This is only happening in development.

**Comment by echan00** [comment]
Same here, also having this issue

**Comment by honigc** [comment]
I can also confirm, in local development on Rails 5.0.6. Standard installation of MiniProfiler with no customizations. Hitting http://localhost:3001/mini-profiler-resources/jquery.tmpl.js directly in a browser, half the time it loads the JS correctly; the rest of the time the requests isn't being handled by the gem, instead making it all the way through to the Rails router. Same behavior observed with the other mini-profiler files.

```
ActionController::RoutingError (No route matches [GET] "/mini-profiler-resources/jquery.tmpl.js"):

actionpack (5.0.6) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
[...other middleware...]
rack-mini-profiler (0.10.7) lib/mini_profiler/profiler.rb:171:in `call'
railties (5.0.6) lib/rails/engine.rb:522:in `call'
```

**Comment by honigc** [comment]
I was seeing this as well for the GET requests, but the issue was the `pre_authorize_cb` lambda I was using wasn't consistently granting access when it should've. I've seen no 404s on GET requests since fixing my code.

I have, however, seen sporadic 404s to `[POST] mini-profiler-resources/results`, generally as part of the same page load as other identical POSTs that succeed. Deleting `tmp/miniprofiler/mp_timers_*` sometimes resolves the issue, temporarily.

**Comment by SamSaffron** [comment]
Oh, I would always recommend memcached or redis as your backend, if you are
using the file backend this can go wrong when site is served off multiple
machines.

**Comment by honigc** [comment]
That's true, and that's what I'm doing in other envs, but for local development I'm using the file backend for simplicity. It's only serving off a single machine, so I would think this would work.

**Comment by brandoncc** [comment]
I have the same issue on Heroku production but only for POST requests.

**Comment by brandoncc** [comment]
Actually, I think I am mistaken. I had it for GET requests and now rollbar grouped all of my 404s under that request, so it kept telling me I was experiencing the mini profiler issue, but I wasn't anymore. Sorry!

**Comment by abhishek77in** [comment]
Similar issue here `ActionController::RoutingError (No route matches [POST] "/mini-profiler-resources/results")`
