### ISSUE TITLE
What's the performance hit of rack-mini-profiler?

### ISSUE THREAD

**Issue by feliperaul** [MiniProfiler/rack-mini-profiler#323]
Is there anywhere I can read more about the performance hit of using rack-mini-profiler, specially in production env?

Is there a difference between using FileStore or RedisStore, or the file is written only after the request is completed so it doesn't slow it down? But can it be slowing down other requests reducing server response time?

Lastly, could using a lot of `Rack::MiniProfiler.step("xxx")` reduce performance or the impact is negligible?

Sorry in advance if this is not the best place to ask this, but I want to know more about the performance hit of the profilling itself and I have no idea how to benchmark it.

**Comment by SamSaffron** [comment]
Ideally the best place to discuss this is on: https://community.miniprofiler.com/
