### ISSUE TITLE
chrome.loadTimes() is deprecated

### ISSUE THREAD

**Issue by t27duck** [MiniProfiler/rack-mini-profiler#329]
Latest Chrome version (version 64) is bringing up depreciation warning regarding the use of `chrome.loadTimes()`

![chrome-dep](https://user-images.githubusercontent.com/545604/35510207-3c6ad9d0-04c5-11e8-8010-1e60687365da.png)

Relevant Chrome information page: https://www.chromestatus.com/features/5637885046816768

Relivant line in includes.js (in master): https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/html/includes.js#L113

**Comment by SamSaffron** [comment]
Would love a PR to fix this.

**Comment by MikeRogers0** [comment]
I'd love to open a PR for this, I think replacing https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/html/includes.js#L113-L122 with:

```
var paintMetrics = performance.getEntriesByType("paint");

if(paintMetrics !== undefined && paintMetrics.length > 0){
  paintMetrics.forEach((paintMetric)=>{
    clientPerformance.timing["paintMetric.name"] = paintMetric.startTime;
  });
}
```

**Comment by SamSaffron** [comment]
looks good idea, can you give it a shot?

**Comment by mathyoudawson** [comment]
Can we close this as the the PR has been merged?
@SamSaffron

**Comment by SamSaffron** [comment]
sure! thanks for reminding me.
