### ISSUE TITLE
FireFox V25.0.1: too much recursion.

### ISSUE THREAD

**Issue by relicmelex** [MiniProfiler/rack-mini-profiler#33]
On initial load of all pages in our ruby application 4 async calls get sent out to the mini-profiler url, and then I get 4 'too much recursion' errors. And in the meanwhile (3 minutes) my browser hangs, and crashes regularly. If you need more information to replicate the bug, please let me know.

Env:
FF 25.0.1
OSX: 10.7.5
 -MacBook Pro 17"

**Comment by jonathanhefner** [comment]
Firebug was [deprecated in 2017](https://hacks.mozilla.org/2017/10/saying-goodbye-to-firebug/), so I think this issue can be closed?

**Comment by SamSaffron** [comment]
Yeah Firebug is such a blast from the past! I have not seen this issue in years. Agree we should close.
