### ISSUE TITLE
Behavior erratic when using :whitelist  and authorize_request mode

### ISSUE THREAD

**Issue by jeffblake** [MiniProfiler/rack-mini-profiler#334]
By erratic I mean, the widget appears randomly with no discernible pattern. For example, I have a page that will load 2 JSON calls on page load. With the mode set to `:allowall`, in dev OR production, everything works wonderfully. With whitelist mode, things fall apart:

Call 1: (page load): shows in widget maybe 50% of the time
Call 2: Ajax #1, same as call 1
Call 3: Ajax #2, I can never get this call to appear with whitelist mode on.

I've made sure `authorize_request` is being called for all 3 requests. I'm positive that's working.

I have `require: false` in Gemfile.

Initializer:

```
require "rack-mini-profiler"

Rack::MiniProfilerRails.initialize!(Rails.application)
# https://github.com/MiniProfiler/rack-mini-profiler/issues/224
Rails.application.middleware.swap(Rack::MiniProfiler, nil)
Rails.application.middleware.delete(nil)
Rails.application.middleware.insert_after(Rack::Deflater, Rack::MiniProfiler)
```

ApplicationController:

```
  before_action do
    Rack::MiniProfiler.authorize_request if admin_user_signed_in?
  end
```

Any clues? Is there a debug mode?

**Comment by z4ppy** [comment]
Hello,

Same here, but never works with :whitelist (all good in dev or with :allowall)

   before_action do                                                                                                                                                                                                                          
      Rack::MiniProfiler.authorize_request      (allow all for fun and test)                                                                                                                                                                                             
   end  

I had this error : 

ActionController::RoutingError (No route matches [GET] "/mini-profiler-resources/includes.js"):

**Comment by dmitrytrager** [comment]
How do you specify whitelist?
