### ISSUE TITLE
Example for use in web api?

### ISSUE THREAD

**Issue by nybroe** [MiniProfiler/rack-mini-profiler#336]
I really love MiniProfiler and am now working on a project using Angular5 in the client application and WebApi2 in the backend application. Setting up the api as the examples suggest doesn't work out of the box. Do you have an example to show api application request data in the client application?

**Comment by slhck** [comment]
Same here, did you find any solution? It seems very unintuitive.

**Comment by shved** [comment]
@nybroe if I've got your question right, you just missed this readme section: https://github.com/MiniProfiler/rack-mini-profiler#miniprofilers-speed-badge-on-pages-that-are-not-generated-via-rails
