### ISSUE TITLE
Rack 0.10.7 now requires Ruby 2.1 as a minimum version, but can be installed on older rubies

### ISSUE THREAD

**Issue by eirvandelden** [MiniProfiler/rack-mini-profiler#338]
What I did:
- have Rails project that runs on Ruby 2.0.0-p353
- add `gem 'rack-mini-profiler'` to Gemfile and install `0.10.7`
- Bundle installed succesfully
- run `bundle exec rails s`
- Go to `root` page

What I Expected:
- Index page shown with badge

What I Got:
```
Unexpected error while processing request: uninitialized constant Process::CLOCK_MONOTONIC
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/rack-mini-profiler-0.10.7/lib/mini_profiler/profiler.rb:152:in `call'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.13/lib/rails/engine.rb:511:in `call'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.13/lib/rails/application.rb:97:in `call'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/rack-1.5.5/lib/rack/handler/thin.rb:16:in `run'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/rack-1.5.5/lib/rack/server.rb:264:in `start'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.13/lib/rails/commands/server.rb:84:in `start'
	/Users/me/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.13/lib/rails/commands.rb:76:in `block in <top (required)>'
```

According to https://github.com/ruby-concurrency/concurrent-ruby/issues/256 and https://gitlab.com/gitlab-org/gitlab-shell/issues/69 Process::CLOCK_MONOTONIC (which was introduced in rack-miniforiler in [pull request 320](https://github.com/MiniProfiler/rack-mini-profiler/pull/320)) is a Ruby 2.1 feature.

Rubygems.org still states that `rack-mini-profiler` requires Ruby 1.9 (https://rubygems.org/gems/rack-mini-profiler)

**Comment by SamSaffron** [comment]
Happy to drop everything below 2.2 officially in the gemspec and readme. per: https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/

If people want older Ruby support they are going to have to dig through old gems. 

Can you do a PR for this?

**Comment by eirvandelden** [comment]
Done. See #339

**Comment by dmtroyer** [comment]
@eirvandelden do you know which version of rack-mini-profiler is the latest to support 1.9.3? Thanks.

**Comment by eirvandelden** [comment]
I guess 0.10.6 or .5. I'd have to check after the weekend.

With kind regards , 
Etienne



Groetjes, 
Etienne

**Comment by dmtroyer** [comment]
sorry, I deleted my comment as I figured it out pretty quickly and it didn't necessarily seem relevant to the issue. I had asked which version of rack-mini-profiler supported ruby 1.9.3. The answer is 0.10.6.

(I'm stuck in jruby 1.7.27 land 👎)

**Comment by MeetChavda** [comment]
remove this gem `gem 'rack-mini-profiler'`
and before remove, clear Gemfile.lock  and 
run `bundle`
hope that working
