### ISSUE TITLE
Postgres time being assigned to puma despite correct order of gems in Gemfile

### ISSUE THREAD

**Issue by stevemadere** [MiniProfiler/rack-mini-profiler#342]
Per the instructions in the Readme, I was careful to add the statement 
```ruby 
gem 'rack-mini-profiler'
```
to my Gemfile below the statement 
```ruby
gem 'pg'
```
Nonetheless, all of my flamegraphs come out with big gaps in them corresponding to database accesses.  In those cases, the time is attributed to puma-2.14.0/lib/rack/handler/puma.rb:14

![screen shot 2018-03-22 at 11 52 03 am](https://user-images.githubusercontent.com/4029925/37785207-92aa7e92-2dc7-11e8-88fb-1db4f5324313.png)

Any idea why this is happening?

**Comment by SamSaffron** [comment]
Can you zoom in on the actual frames to see the actual method names?

**Comment by stevemadere** [comment]
Like this?

```
… puma-2.14.0/lib/rack/handler/puma.rb:14:in `#.run' | (36 samples - 29.03%) (7 exclusive - 5.65%)
-- | --
… rack-1.6.4/lib/rack/server.rb:247:in `Rack::Server#start' | (36 samples - 29.03%)
… railties-4.2.6/lib/rails/commands/server.rb:74:in `Rails::Server#start' | (36 samples - 29.03%)
… railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `block in Rails::CommandsTasks#server' | (36 samples - 29.03%)
… railties-4.2.6/lib/rails/commands/commands_tasks.rb:71:in `Rails::CommandsTasks#server' | (36 samples - 29.03%)
… railties-4.2.6/lib/rails/commands/commands_tasks.rb:36:in `Rails::CommandsTasks#run_command!' | (36 samples - 29.03%)
… railties-4.2.6/lib/rails/commands.rb::in `' | (36 samples - 29.03%)
/Users/stevemadere/src/gowinepro/bin/rails::in `' | (36 samples - 29.03%)
bin/rails::in `' | (36 samples - 29.03%)
```

**Comment by SamSaffron** [comment]
sorry I mean in the flame graph, you zoom in with the mouse wheel and it shows the method name in the frame

**Comment by stevemadere** [comment]
![screen shot 2018-03-22 at 10 18 52 pm](https://user-images.githubusercontent.com/4029925/37809839-1bf6a9b2-2e1f-11e8-97a8-d3bd19884441.png)

**Comment by jaydorsey** [comment]
I see similar behavior on an app I'm profiling. It looks like large swathes of time attributed to puma, but it's most definitely postgres-related (long running queries)

I did try to `export RACK_MINI_PROFILER_PATCH="pg"` and restart the server to see if that would fix it but no luck

**Comment by nateberkopec** [comment]
This is exactly as expected.

When you wait on an I/O operation when running a multithreaded Puma configuration, the current thread switches from the thread in the threadpool running your app to the thread which accepts new requests in Puma. That's what these gaps are that you're seeing.
