### ISSUE TITLE
click() shorthand is deprecated at jQuery 3

### ISSUE THREAD

**Issue by TiSer** [MiniProfiler/rack-mini-profiler#343]
After migration to jQuery 3 I noticed this when using the migration helper:
<img width="533" alt="screen shot 2018-03-26 at 11 52 47 am" src="https://user-images.githubusercontent.com/617537/37896587-c9855478-30ec-11e8-82e6-b270cc985595.png">

Affected code:
https://github.com/MiniProfiler/rack-mini-profiler/blob/d4ede4498ff3ab0c1148d5179e676d717307e038/lib/html/includes.js#L183
Now it should be:
`button.on("click", function () { buttonClick(button, popup); });`

About click() shorthand deprecation at jQuery 3 docs: https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnclick-event-shorthand-is-deprecated

**Comment by TiSer** [comment]
PR: https://github.com/MiniProfiler/rack-mini-profiler/pull/346

**Comment by jonathanhefner** [comment]
This can be closed since #346 has been merged.

**Comment by SamSaffron** [comment]
jQuery no longer ships with MP :confetti_ball:

**Comment by neelesh-s** [comment]
$btns.click(function (e).What shall I use instead of this?

**Comment by Bibendus83** [comment]
> 
> 
> $btns.click(function (e).What shall I use instead of this?

Check OP,
```button.on("click", function () { buttonClick(button, popup); });```
