### ISSUE TITLE
No bindings for clients that use the new javascript fetch API

### ISSUE THREAD

**Issue by shyam-habarakada** [MiniProfiler/rack-mini-profiler#348]
I noticed that we don't have any bindings that refresh profiler results when the page is using the `fetch` API https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

Does anyone have an update for this in the works? If not I can try to get a PR going.

**Comment by SamSaffron** [comment]
interesting, yeah I would like to have that added, can you make a PR

**Comment by shyam-habarakada** [comment]
## design discussion

I was looking into this more — the current pattern with other libraries like jQuery and XHR appears to be to patch or hook into available extension points so that inspecting and grabbing the `X-MiniProfiler-Ids` from headers and passing that through to the `fetchResults` method.

Unfortunately the fetch API doesn't seem to have hooks that we can incorporate into and the promise based design of it makes patching it not a very attractive option. Strictly technically speaking it seems feasible to patch `fetch` and wrap the promises it returns so that we can intercept and capture the headers. Another option is to expose a method in this library that _any_ javascript could invoke to just pass in `X-MiniProfiler-Ids`. In our use of fetch for instance, we can then add something into the promise chain to do exactly that. Less intrusive but won't work by default.

Thoughts/feedback?

**Comment by shyam-habarakada** [comment]
@SamSaffron PR linked above. Thanks

**Comment by gregmolnar** [comment]
This one can be closed since it is fixed in #351
