### ISSUE TITLE
Can't figure out how to get a flamegraph for ajax post request.

### ISSUE THREAD

**Issue by CyborgMaster** [MiniProfiler/rack-mini-profiler#350]
I can see the profiler badge for ajax requests by hitting any html page (it shows all of requests since the last html load), however I can't figure out how to get the flamegraphs for those requests.  Am I missing something?

**Comment by CyborgMaster** [comment]
#352 is the way I ended up working around it for now.  

Because this is a JSON API post, there is no way to return the flamegraph directly to the browser, so the only option would be to cache it and return it on the next HTML request, in a similar fashion to the current summary stats that appear in the profile badge.  However, flamegraphs can be very large (10s or even 100s of megabytes) so caching many of these may be prohibitive.  

My solution was to add an option to save the flamegraph html to a file, where I can open it in a separate browser tab.

This is just a quick solution I threw together, but it turned out to be very effective for my use case. 
 Thoughts?

**Comment by OsamaSayegh** [comment]
Perhaps I'm missing something here, but for you can append `?pp=flamegraph` to your URL and you'll get flamegraph for your request, this even works for JSON routes e.g. in any Discourse site (assuming I logged in as admin) I can do `/latest.json?pp=flamegraph` and I get a flamegraph. I think you're already aware of that, but does that not work for you or am I missing something?

**Comment by CyborgMaster** [comment]
Yes, but in this case it's not a page load that is making the request, it's an Angular SPA using XHR.  Angular expects the response to be json and not html and then crashes.  Yes, I could do a manual page load instead of letting the SPA do it, but  the problem is that the slowdown only occurs in a particular sequence of API calls that the SPA is performing, so it's not feasible to have it be a full page load.

**Comment by OsamaSayegh** [comment]
Ok, I think I understand your use case now: Your use case is that you want a JSON request to still return a JSON response, but you also want to somehow see the flamegraph for that request. You can't use `?pp=flamegraph` for two reasons:

1. `?pp=flamegraph` changes the response type for JSON to HTML;
2. in your application the slowdown occurs after a sequence of API calls, and if you were to use `?pp=flamegraph` there would be a quite a bit of manual work involved.

Does this sound right?

**Comment by CyborgMaster** [comment]
Nailed it!  That describes the situation very well.

**Comment by feliperaul** [comment]
Same here @OsamaSayegh

**Comment by OsamaSayegh** [comment]
I think this is now possible thanks to https://github.com/MiniProfiler/rack-mini-profiler/commit/020cd4f510134ef933f6a8ff2eba6a6f5f0331b1?

**Comment by feliperaul** [comment]
@OsamaSayegh You're totally right; I got this yesterday after posting here. 

Would you consider a pull request improving the documentation regarding this?

**Comment by OsamaSayegh** [comment]
Yes, absolutely! thanks!

**Comment by feliperaul** [comment]
@OsamaSayegh #512, closing this. I think this issue can be closed! Cheers.

**Comment by OsamaSayegh** [comment]
Merged, thanks a lot!
