### ISSUE TITLE
Profiling output to log message

### ISSUE THREAD

**Issue by davidwinter** [MiniProfiler/rack-mini-profiler#365]
Is it possible to use the profiler to output the high level profiling results (such as number of database queries, time to response etc) to a log message? I'd like to integrate it into an API app that doesn't have a UI frontend.

**Comment by kbrock** [comment]
Hello @davidwinter 

To profile methods that are not ui methods, try out https://github.com/MiniProfiler/rack-mini-profiler#profiling-specific-methods

Not sure if you want to output the results to the logs or if it is better to output the profile_id and view the results with another ui/cli - storing in redis makes it easy to view the results.

I was playing around with this concept for a while in https://github.com/kbrock/cli_mini_profiler
It has a capture component to make it easier to capture and a cli component to view captured stacks - with varying level of details.

I found that while looking at these stacks, sometimes I wanted to dedup queries (show all queries to the database) and other times I wanted full stack traces for each query. Just outputting to a log file would not work for me. but we are different people.

Never got it far enough to move back into rack-mini-profiler, but does give you an idea of what can be done.

Best of luck

**Comment by mathyoudawson** [comment]
@kbrock Can we close this?

**Comment by SamSaffron** [comment]
It is very feasible to just create a special storage class that logs to file or something, also you could use sample based profiling. 

That said, I agree there is no point keeping this open for years.
