### ISSUE TITLE
Error loading resources when strict MIME checking is enabled

### ISSUE THREAD

**Issue by fracklen** [MiniProfiler/rack-mini-profiler#366]
Hey

I just deployed your awesome gem to a site that has rather strict security.
Among the security settings are `X-Content-Type-Options: nosniff`

The console in Chrome says:
```
Refused to apply style from 'https://example.org/mini-profiler-resources/includes.css?v=251162ee7dc30da30d5370581c664510' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

```
Refused to execute script from 'https://example.org/mini-profiler-resources/jquery.tmpl.js?v=251162ee7dc30da30d5370581c664510' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

From what I can read in the source, anything not an XHR gets `Content-Type: text/html`

I'll try to throw a PR tomorrow if possible.

**Comment by SamSaffron** [comment]
thanks, yeah we want to server files with the correct mime type for sure.

**Comment by matthutchinson** [comment]
+1 I'm seeing this too, on a default Rails 6 app served over HTTPs

**Comment by OsamaSayegh** [comment]
@fracklen is this still an issue? Both in production and locally I can see `Content-Type` is set correctly for Mini Profiler JS and CSS assets. To be extra sure I didn't miss anything, I temporarily added `X-Content-Type-Options: nosniff` to Mini Profiler assets and didn't see any MIME errors in my browser console.

That said, if you still see this on the latest version of MP, please provide more details about your site and I'll reopen. Thanks!
