### ISSUE TITLE
/mini-profiler-resources/includes.js not worked in production with a 404 Not Found

### ISSUE THREAD

**Issue by zw963** [MiniProfiler/rack-mini-profiler#369]
When run rack-mini-profiler in our production multi-container environments, got following error:

![image](https://user-images.githubusercontent.com/549126/50195013-59db1680-0378-11e9-902e-3e57de9e8931.png)

But same url, if opened in a seprate browser tab, it worked!

![image](https://user-images.githubusercontent.com/549126/50195046-770fe500-0378-11e9-9da4-d81c0c74811a.png)

### config

Rails 5.2.0
Ruby 2.5.1
Sequel 5.10.0
graphql 1.8.5

With zero config, except add following config to controller entrypoint.

```rb
if request.headers['rack-mini-profiler-header'] == 'true'
      Rack::MiniProfiler.authorize_request
end
```

All worked in staging with a single-container environment.

Thanks

**Comment by OsamaSayegh** [comment]
Is this still an issue? Like Sam said, you need to use redis or memcached store in multi-container environment. I'm going to close this for now, but let me know if you've switched to redis or memcached and you still see 404 errors.

**Comment by zw963** [comment]
Sorry for delay, it working when use with redis, thank you.
