### ISSUE TITLE
Sass gem deprecated

### ISSUE THREAD

**Issue by P9GIT** [MiniProfiler/rack-mini-profiler#372]
Hi team.

Thanks for this great and useful gem.

This gem depends on the sass gem which is deprecated and shortly will be unmaintained: https://sass-lang.com/ruby-sass

Any plans for migrating away to e.g. the SassC gem?

Best regards, Thomas.

**Comment by SamSaffron** [comment]
I would love to see this migrated to sassc, keep in mind there is no runtime dependency this is only build time so it is not urgent or anything.

**Comment by P9GIT** [comment]
@SamSaffron 

Let's hope so. Sassc should be a drop-in replacement.
Thanks for your answer.
