### ISSUE TITLE
getting started docs

### ISSUE THREAD

**Issue by jrochkind** [MiniProfiler/rack-mini-profiler#373]
The only real "getting started" docs provided (like, how do you even use this thing?) that I can find are the [link to 2012 announcement post](http://samsaffron.com/archive/2012/07/12/miniprofiler-ruby-edition). 

However, that blog post now has all broken images, both inline images and links to images, which makes it quite a bit harder to understand, since it used screenshots as important narrative.

**Comment by SamSaffron** [comment]
I totally support improving docs ... and my blog post being so ugly and
full of broken images is a problem I will addres.

**Comment by SamSaffron** [comment]
@jrochkind blog post is now fixed, thanks heaps for alerting me about it.
