### ISSUE TITLE
Disable pp= queries for non-admin users

### ISSUE THREAD

**Issue by Kani999** [MiniProfiler/rack-mini-profiler#374]
Hello,

I'm about to set up rack-mini-profiler on our production environment.
I've set up `Rack::MiniProfiler.authorize_request` at application controller, so common users are not able to see the mini_profiler.

But if I sent the request with: 
  - `?pp=profile-memory`
  - `?pp=profile-gc`
  - `?pp=analyze-memory`

The common user can see the results.

How can I disable these paths for the non-admin user accounts.

Thanks

**Comment by nkblue** [comment]
https://github.com/MiniProfiler/rack-mini-profiler#access-control-in-non-development-environments

**Comment by Kani999** [comment]
@nkblue - Yes I've setted up this security. I mention it in the question.

I'm closing the ticket. Queries are not showed to non-admin users as expected.
The problem was that the results were cached in my browser.
