### ISSUE TITLE
Using mini profiler outside of request scope

### ISSUE THREAD

**Issue by driv3r** [MiniProfiler/rack-mini-profiler#378]
Hi,

First of all thanks for all great work put into the project, it's awesome!

One thing I was struggling with, is that I can't really use it standalone, outside of request scope as there's too much coupling happening in the rack middleware layer. I was wondering if there were any plans to refactor it (i.e. with the move towards `MiniProfiler/ui`)? Maybe also something I could help with.

Best,
Leszek

**Comment by kbrock** [comment]
Hello @driv3r 

The readme has an example of profiling code [[here]](https://github.com/MiniProfiler/rack-mini-profiler#profiling-arbitrary-block-of-code)

If that doesn't work for you, I did have the need to profile code as well.
My needs are a little different, and my code has probably diverged a little over the past few years.

But the high level can be found here:
https://github.com/kbrock/cli_mini_profiler/blob/master/lib/cli_mini_profiler/profiler.rb#L68

```ruby
def profile(name = "method")
  env = {'RACK_MINI_PROFILER_ORIGINAL_SCRIPT_NAME' => "http://localhost:3000" }

  page_struct = storage.current(env).page_struct
  page_struct[:name] = name
  before = Time.now
  yield
  after = Time.now
  page_struct[:root].record_time((after - before) * 1000)
#    storage.set_unviewed(page_struct[:user], page_struct[:id])
  storage.save(page_struct)
  [page_struct[:id], d]
ensure
  ::Rack::MiniProfiler.current = nil
end
```

Determining storage is a little more tricky, but there may now be a way to do that from the code base itself.

Best,
Keenan
