### ISSUE TITLE
jQuery regression from #381

### ISSUE THREAD

**Issue by francoisjacques** [MiniProfiler/rack-mini-profiler#385]
I guess this one is for @OsamaSayegh

#381 introduced a regression in [includes.js](https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/html/includes.js#L767):

```
load(options.path + "jquery.1.7.1.js?v=" + options.version, function() {
```

It breaks when rack-mini-profiler is loaded in an application not using jquery already.

**Comment by SamSaffron** [comment]
oh ... we now removed jquery, so this is now solved!
