### ISSUE TITLE
rack-mini-profiler-1.0.2/lib/patches/db/mysql2.rb:8: [BUG] Segmentation fault

### ISSUE THREAD

**Issue by peakjason** [MiniProfiler/rack-mini-profiler#397]
[ruby_2019-08-28-110219_cinqodemaco.crash.txt](https://github.com/MiniProfiler/rack-mini-profiler/files/3551554/ruby_2019-08-28-110219_cinqodemaco.crash.txt)

Using ruby 2.5.0 and rails 4.2.10 under rvm. I'm trying to run Rails ERD to make an entity relationship diagram (see https://voormedia.github.io/rails-erd/)

When I run:

`bundle exec erd`

I get this error (and then a massive stack trace, attached):

```
/usr/local/rvm/gems/ruby-2.5.0@global_app/gems/rack-mini-profiler-1.0.2/lib/patches/db/mysql2.rb:8: [BUG] Segmentation fault at 0x0000000000017831
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin18]
```

I also get the same error when I do a rake db:migrate.

Here's the line in mysql2.rb:

`return each_without_profiling(*args, &blk) unless defined?(@miniprofiler_sql_id)
`

**Comment by SamSaffron** [comment]
This is either a bug in ruby or more likely a bug in mysql2. 

There is no unmanaged code in mini profiler, it is simply passing the call on to mysql2.
