### ISSUE TITLE
cannot load such file -- rack-mini-profiler (LoadError)

### ISSUE THREAD

**Issue by ahvahsky2008** [MiniProfiler/rack-mini-profiler#398]
I have
```
Ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
Rails 5.0.6
```
Try deploy app with passenger but it rise error

``
cannot load such file -- rack-mini-profiler (LoadError)
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
  /home/otzovy/releases/20190905110757/config/initializers/rack_profiler.rb:2:in `<main>'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `load'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `block in load'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/engine.rb:648:in `block in load_config_initializer'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/notifications.rb:166:in `instrument'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/engine.rb:647:in `load_config_initializer'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/engine.rb:611:in `each'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/engine.rb:611:in `block in <class:Engine>'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `instance_exec'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `run'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:44:in `each'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:44:in `tsort_each_child'
  /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:415:in `call'
  /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /usr/local/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:54:in `run_initializers'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/application.rb:352:in `initialize!'
  /home/otzovy/releases/20190905110757/config/environment.rb:5:in `<top (required)>'
  config.ru:4:in `require'
  config.ru:4:in `block in <main>'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
  /home/otzovy/shared/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
``

**Comment by AFlowOfCode** [comment]
I came across this when deploying an app to Heroku. Simple mistake for me, I realized I forgot to take the gem out of the :development group in my Gemfile and make it available to all environments. When my initializer tried to require it, this happened and the build broke.
