### ISSUE TITLE
No database parameters in rack-mini-profiler window (filtered?)

### ISSUE THREAD

**Issue by unavailabl3** [MiniProfiler/rack-mini-profiler#404]
Hello! All parameters of database query are not shown in profiler web window.
There is 
`SELECT  "items"."id" FROM "items" WHERE "item"."category_id" IN ($1,$2,$3) LIMIT $4;
`
But I need:
`SELECT  "items"."id" FROM "items" WHERE "item"."category_id" IN (11,12,13) LIMIT 20;
`
Why params may be filtered? In other project all is normal.

Rails 5, Ruby 2.5.1, Postgresql, **rack-mini-profiler 1.0.2**

**Comment by SamSaffron** [comment]
Yes we should add some support for prepared statements here.

**Comment by kbrock** [comment]
I think the parameters do make their way into the data structure.
I'm guessing the issue would be while displaying the sql statement

**Comment by suryanarayanan035** [comment]
Hello @unavailabl3 , Like @kbrock said the config is already there. We just need to enable it. Please add this line of code  to your rack-mini-profiler initialization or configuration file.
`Rack::MiniProfiler.config.max_sql_param_length = 100 # please add a parameter value which makes sense to you`

After adding the config you will be able to see the params in the badge just like below
![localhost_3000_items](https://github.com/MiniProfiler/rack-mini-profiler/assets/32085008/9854eb3c-ada2-4d75-846f-1cd6d19c9a35)

**Comment by kbrock** [comment]
Thanks @suryanarayanan035 - I totally forgot how to enable this -- https://github.com/MiniProfiler/rack-mini-profiler/pull/202

**Comment by kbrock** [comment]
@unavailabl3 are you all set on this one? I think the above solution should meet your needs

**Comment by thomaswitt** [comment]
@kbrock A quick question - when I enabled this parameter (which is by the way not documented in README.md), I still see in the profiler window truncated SQL queries. Is there any way to expand all SQL queries in the view to see the full output? Even in the share page it's shortened.

**Comment by kbrock** [comment]
@thomaswitt the full query is stored. So if what you are seeing is truncated, that would be in the UI.

I'm not aware of any parameters used to modify that.
