### ISSUE TITLE
Flaky specs in spec/lib/profiler_spec.rb

### ISSUE THREAD

**Issue by jethroo** [MiniProfiler/rack-mini-profiler#422]
While opening a PR for the project I noticed due to one failng build that there are flaky specs:

```
rspec ./spec/lib/profiler_spec.rb:116 # Rack::MiniProfiler step typical usage measures total duration correctly

rspec ./spec/lib/profiler_spec.rb:124 # Rack::MiniProfiler step typical usage measures outer duration correctly
```

The related build: https://travis-ci.org/MiniProfiler/rack-mini-profiler/jobs/617729576?utm_medium=notification

While renunning those tests they were green again. So there seems to be a timing issue because the expected values are off only by one second. 

![Bildschirmfoto 2019-11-27 um 14 52 46](https://user-images.githubusercontent.com/2653013/69729375-79e98d00-1126-11ea-994b-b4cd25cd7e47.png)

**Comment by SamSaffron** [comment]
Ouch, would be awesome to fix this, can you look at a PR?

**Comment by jethroo** [comment]
sure can try to reproduce and hunt down the issue ;)

**Comment by jethroo** [comment]
I think the issue is that the result of `#duration_ms` is converted to integer thus introducing a rounding error, the calculation of duration itself is operating on floats so no issues there, so one can easily change the matching to use the `be_within` matcher. 

I have a PR open on my fork (https://github.com/jethroo/rack-mini-profiler/pull/1/files#diff-4253539b8e9545261114a75d16843fe2R118) and will open one for the origin as soon as my other PR #424 is merged for rendering the build green again.
