### ISSUE TITLE
Wrong description of skip_schema_queries in Readme

### ISSUE THREAD

**Issue by semaperepelitsa** [MiniProfiler/rack-mini-profiler#432]
In Readme skip_schema_queries is described as:

> 'true' to log schema queries.

Isn't it the opposite?

> 'true' to skip schema queries.
> 'false' to log schema queries.

**Comment by SamSaffron** [comment]
Yes I think you are correct, PR to clean up the docs?

**Comment by OsamaSayegh** [comment]
Thank you @semaperepelitsa, fixed in https://github.com/MiniProfiler/rack-mini-profiler/commit/c8b19a458fc6e892fc388caf2897067fa94fb2d1.
