### ISSUE TITLE
Injected content doesn't play well with CSP nonces

### ISSUE THREAD

**Issue by viraptor** [MiniProfiler/rack-mini-profiler#439]
When setting up CSP in rails, the mini-profiler is a resource which is hard/impossible to manage properly with script/style nonces. When using domain whitelists, you can add `'self'` to work around the problem, but once you use nonces, the domain whitelist is disabled.

It would be great if there was a setting enabling injecting `nonce="#{content_security_policy_nonce}"` when using mini-profiler with rails.

**Comment by richhollis** [comment]
I've sumitted a PR for this: https://github.com/MiniProfiler/rack-mini-profiler/pull/495
