### ISSUE TITLE
Use redis `exists?` 

### ISSUE THREAD

**Issue by mylesboone** [MiniProfiler/rack-mini-profiler#445]
`Redis#exists(key)` will return an Integer in redis-rb 4.3, if you want to keep the old behavior use `exists?` instead.

**Comment by mylesboone** [comment]
#446 would fix this.

**Comment by OsamaSayegh** [comment]
Fixed by https://github.com/MiniProfiler/rack-mini-profiler/commit/7ad4279dab36058386cbd96e8d251e7c15f255f9.
