### ISSUE TITLE
Loss of Detailed SQL Profiling

### ISSUE THREAD

**Issue by billy1kaplan** [MiniProfiler/rack-mini-profiler#460]
I have a Rails 5 app running rack-mini-profiler version 1.0.2 with a Postgres 9.6 database. Recently, I discovered that the SQL profiler data seemed a lot less detailed. I did a binary search through my commit history and discovered that this behavior seems to have started when upgrading from Rails 5.0.7 to Rails 5.1.7 and has continued in Rails 5.2.

The issue also persists after upgrading to rack-mini-profiler version 2.0.4

A summary of this particular commit version upgrade:
- rails 5.0.7 -> rails 5.1.7
- dotenv-rails 2.1.1 -> dotenv-rails 2.7.5
- responders 2.3.0 -> 2.4.1

Here is what the SQL profiler looks like before upgrading to Rails 5.1.7...
<img width="1359" alt="profiler_before" src="https://user-images.githubusercontent.com/12505097/91338108-6a28d300-e7a2-11ea-9d6d-05eb64a70e88.png">

And after...
<img width="1394" alt="profiler_after" src="https://user-images.githubusercontent.com/12505097/91338104-69903c80-e7a2-11ea-846b-d42b194f436e.png">

Afterwards, the SQL profiler seems to lose all of the application SQL profiling. How do I get back the original, detailed SQL profiling?

**Comment by billy1kaplan** [comment]
Resolved by updating other dependencies

**Comment by jaydorsey** [comment]
> Resolved by updating other dependencies

@billy1kaplan do you remember which dependencies you updated to resolve this?

I've completely lost all SQL profiling and as I've tried to bisect recent changes in my Gemfile, I'm at a loss determining what affected the SQL profiing

**Comment by billy1kaplan** [comment]
Hey @jaydorsey, for us it ended up being a combination of `rack-mini-profiler` and `pg` that was causing the issue.

We upgraded from:
`pg`: `0.18.4` -> `1.2.3`
`rack-mini-profiler`: `1.0.2` -> `2.1.0`
to resolve this.

Hope that helps!
