### ISSUE TITLE
speed badge shows double entries for each request

### ISSUE THREAD

**Issue by joelcahalan** [MiniProfiler/rack-mini-profiler#472]
I have tested across three browsers and all of them had this behavior on my mac. My colleague's machine does not have this behavior for the same rails app. Any thoughts on how to debug this would be appreciated.

**Comment by kei-p** [comment]
I've encountered the same thing.
I inspected how it work fetch mini_profile results and found that `onload` function is called twice each one request at here

https://github.com/MiniProfiler/rack-mini-profiler/blob/338cdd1a3c6f71a6ade103708a3d613ac9021e70/lib/html/includes.js#L139-L161

**Comment by kei-p** [comment]
I have found the cause of this.
In my case, it seems to have been caused by a change in xhr's behavior due to the `bullet` gem.

**Comment by kbrock** [comment]
is this resolved?
Is there a particular action that can come from this issue?
