### ISSUE TITLE
Improvements for development section

### ISSUE THREAD

**Issue by ceritium** [MiniProfiler/rack-mini-profiler#499]
Hi, I want to contribute, but I found some issues that maybe you could clarify.

## `rake spec` fails
it is just on my machine? Do we need a specific setup? I am running `ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]`

```
 1) Rack::MiniProfiler gc profiler should return a report
     Failure/Error: expect(last_response.header['Content-Type']).to eq('text/plain')

       expected: "text/plain"
            got: "text/plain; charset=utf-8"
```

## Required services

It's easy to come across that we need Redis and Memcached for development, but maybe we should add it to the documentation. 

Would it make sense to include a docker-compose file? I would add overhead to the project, because the core team has to maintain that file too.

## `bundle exec rake client_dev`

It only works if I run bundle instal in the root and `website` folders. Is it the expected behaviour? I would reflect it on the readme.
 
What is the difference between `old_site` and `website`? Can we document it? Should we delete it?

I only want to clarify those topics and create some PRs according to the output to improve the readme. Many thanks for your effort and this awesome project.

**Comment by SamSaffron** [comment]
This looks like some change in Rack, we should totally fix it , maybe just change the spec to "includes"

> It only works if I run bundle instal in the root and website folders. Is it the expected behaviour? I would reflect it on the readme.

Yeah we should either improve the rake task or add documentation 

> Would it make sense to include a docker-compose file? I would add overhead to the project, because the core team has to maintain that file too.

I am fine with that if you would like to own maintaining it

> It's easy to come across that we need Redis and Memcached for development, but maybe we should add it to the documentation.

Sure at a minimum I support adding more documentation 

Thanks for investigating these issues!

**Comment by ceritium** [comment]
Thanks for your comments @SamSaffron, I am going to create some PRs. 

Regarding the docker-compose file, I am just going to document the Redis and Memcached.

We can close this issue, in my opinion.
