### ISSUE TITLE
Show gem name somewhere.

### ISSUE THREAD

**Issue by lafeber** [MiniProfiler/rack-mini-profiler#503]
Super simple request, but I think it would be nice if there was a link back to this repo. A '?' sign on the top right of the popup?

See newby questions: 
- https://www.reddit.com/r/rubyonrails/comments/og3p0z/super_new_to_this_does_anybody_know_how_to/
- https://www.reddit.com/r/rails/comments/me9ato/how_to_remove_the_page_loading_time_indicator_in/

I'm willing to create a PR for this.

**Comment by SamSaffron** [comment]
Oh ... PR 100% welcome to improving `?pp=help` it can certainly link to the gem. 

You can already reach there by clicking "more".  (we could move more to the right)
