### ISSUE TITLE
New release for Rails and Hotwire

### ISSUE THREAD

**Issue by ceritium** [MiniProfiler/rack-mini-profiler#509]
Hello, rack-mini-profiler has a recent PR [adding support for turbo-drive](https://github.com/MiniProfiler/rack-mini-profiler/pull/498), and Rails recently merged a PR that replaces "turbolinks" with "turbo"](https://github.com/rails/rails/commit/af7428c4acd0fcf9eed5c7215856594a078f23b7).

We could improve the developer experience by releasing a new version of rack-mini-profiler and adding to the rails generator `enable_hotwire_turbo_drive_support = true`.

**Comment by SamSaffron** [comment]
Sure no problems will push a release now.

**Comment by ceritium** [comment]
Thanks!

**Comment by ceritium** [comment]
Rails PR: https://github.com/rails/rails/pull/43134
