### ISSUE TITLE
MiniProfiler storage failure: undefined method `upcase' for [:exists, "MPRedisStoreha3b3tlmb7rm5r8zcf3a"]:Array

### ISSUE THREAD

**Issue by diegonulinga** [MiniProfiler/rack-mini-profiler#513]
I moved from a single server to k8s, I changed the storage to redis and now I can't see the widget in production and that is the log that I have. 
I tested in my local with redis and works well

Redis version: 6.0.9
Rack mini profiler version: 2.2.1

If you need another information, just ask.
Thanks.

**Comment by jclusso** [comment]
@diegonulinga did you ever figure out your issue?

**Comment by jclusso** [comment]
It appears that disabling the [elastic-apm](https://github.com/elastic/apm-agent-ruby) gem resolves this. This isn't really a solution, but I'm not sure if the problem is in this or in that. @SamSaffron any ideas?

**Comment by diegonulinga** [comment]
> @diegonulinga did you ever figure out your issue?

i couldn't make it work

**Comment by jclusso** [comment]
@diegonulinga were you using elastic-apm?

**Comment by diegonulinga** [comment]
yes, i am using it!

**Comment by jclusso** [comment]
Well my PR linked above fixes it.

**Comment by nateberkopec** [comment]
Fixed on the elastic-apm side.
