### ISSUE TITLE
ArgumentError: comparison of String with 200 failed

### ISSUE THREAD

**Issue by mickeytgl** [MiniProfiler/rack-mini-profiler#521]
We were getting some `MiniProfiler storage failure: Comparison of String with 200 failed` in our app, which it turns out is very similar to Issue #185

<img width="842" alt="CleanShot 2022-02-08 at 15 08 37@2x" src="https://user-images.githubusercontent.com/20502556/153215841-8b95ac88-3b42-4554-8ef7-21a4dbc62a86.png">

**Comment by nateberkopec** [comment]
Marking as wontfix.
