### ISSUE TITLE
Changing the hot key to show/hide mini profiler?

### ISSUE THREAD

**Issue by kendallb** [MiniProfiler/rack-mini-profiler#523]
I did not see this (perhaps I missed it), but is there a way to change what hot key is used to show/hide the mini profiler screen? By default that is Alt-P, but because I float between a Mac and Windows, for years I have used a common set of hot keys on both so Alt-P maps to Ctrl-P for me for printing stuff in the browser. So I would like to somehow remap it to another key I am not using.

**Comment by OsamaSayegh** [comment]
Yes, it's possible to change the keyboard shortcut, see the `toggle_shortcut` config in the README.

**Comment by kendallb** [comment]
Cool thanks. I don't see that in the readme though? Where is it documented so I can figure out how to change it?

**Comment by OsamaSayegh** [comment]
It's documented in the README under the "Configuration Options" section: https://github.com/MiniProfiler/rack-mini-profiler#configuration-options.

![image](https://user-images.githubusercontent.com/17474474/154344164-812a88fe-cd34-44d7-a2bf-0b99021e1839.png)

**Comment by kendallb** [comment]
Dang it! I posted this in the wrong one. I am using the DotNet version :). Gonna close this and repost there. I wonder if it's the same?
