### ISSUE TITLE
fetch_snapshots_overview not implemented for FileStore

### ISSUE THREAD

**Issue by johnnyshields** [MiniProfiler/rack-mini-profiler#535]
#fetch_snapshots_overview method is not implemented for FileStore

This causes a `NotImplementedError` when using FileStore and attempting to access `/mini-profiler-resources/snapshots`

**Comment by adambair** [comment]
Seems similar... https://github.com/MiniProfiler/rack-mini-profiler/issues/470

**Comment by nateberkopec** [comment]
Merging with #470
