### ISSUE TITLE
Cannot see all requests in development

### ISSUE THREAD

**Issue by raquelhortab** [MiniProfiler/rack-mini-profiler#540]
The profiler does not seem to work equally in production than in development.
A request in production:
![Selection_767](https://user-images.githubusercontent.com/19463905/189331271-b389fdeb-a43c-404d-9885-dc767179b040.png)

The same request in dev:
![Selection_768](https://user-images.githubusercontent.com/19463905/189331298-745e3b38-3dbc-482d-9c82-287db5a49963.png)
![Selection_769](https://user-images.githubusercontent.com/19463905/189331304-18eb0064-774c-4569-a985-c5c86ee12b93.png)

I think it might be because in dev, any request is tracked but there might be some maximum of requests shown (it says x10 but only shows 9. Meanwhile, in production only the main page request is tracked (since it is where I'm calling `Rack::MiniProfiler.authorize_request`).

Is there any way I can see all requests when unfolding the profiler info?

**Comment by raquelhortab** [comment]
I have modified the maxTracesToShow value in profiler.rb although it'd be nice if this was customizable via some config file or initialization options

**Comment by gmcgibbon** [comment]
In the latest release, this is configurable via `Rack::MiniProfiler.config.max_traces_to_show`. The default value is 20, but you should be able to change it in an initializer or equivalent. See https://github.com/MiniProfiler/rack-mini-profiler/blob/edbcad3197a1a9db9260b502296cc697f12f1520/lib/mini_profiler/profiler.rb#L754

**Comment by nate-at-gusto** [comment]
One big reason for the difference is usually asset requests. You didn't post what the other URLs are, but I'm guessing since they're so quick is because you are serving your assets from your Rails server when on local, and you're not ignoring those paths in your configuration.
