### ISSUE TITLE
SSL error for Heroku Redis

### ISSUE THREAD

**Issue by nbashaw** [MiniProfiler/rack-mini-profiler#542]
Heroku Redis has a problem with self-signed certificates: https://help.heroku.com/HC0F8CUS/redis-connection-issues

In order to get Rack Mini Profiler to work, I had to add this to my `config/initializers/mini_profiler.rb` file:

```ruby
if Rails.env.production?
  Rack::MiniProfiler.config.storage_options = { 
    url: ENV["REDIS_URL"],
    ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
  }
  Rack::MiniProfiler.config.storage = Rack::MiniProfiler::RedisStore
end
```

Might be helpful to add this to the README, as I suspect a lot of people might run into a similar issue? Or if there is a better fix that doesn't skip SSL verification, I would love to use that, but I haven't been able to figure it out yet.

**Comment by nate-at-gusto** [comment]
Wow. To be honest I'm a bit shocked that this is Heroku's official solution.

**Comment by nbashaw** [comment]
Yeah I'm on the verge of switching to Render. Curious if you have any recommended alternatives?
