### ISSUE TITLE
Not working with Rails 7 (foreman)

### ISSUE THREAD

**Issue by n1xn** [MiniProfiler/rack-mini-profiler#546]
I am using Rails 7 with tailwind and my problem is that I am starting the rails server with `foreman` and a procfile to run multiple services. Unfortunately this breaks the mini profiler and it is not showing up anymore unless I start the application without foreman/procfile. Does anybody know how I can get both working?

**Comment by matt17r** [comment]
I'm using Rails 7 (7.0.3 previously, now 7.0.4.2) with Tailwind and Mini Profiler is working for me. Well, it's showing up anyway, I'm still struggling to get a working flame graph but that's (literally) a separate issue #536. Are you running the server with `bin/dev`? Is it just calling `foreman start -f Procfile.dev`? If so, what's in your Procfile?

FWIW my working procfile has:

```
web: bin/rails server -p 3000
js: yarn build --watch
css: yarn build:css --watch
```

What version of Ruby are you using?

What version or RMP?

What version of Foreman?

What command are you using to start the app without Foreman?

Is it reproducible in a new skeleton app?

**Comment by n1xn** [comment]
Sorry for the late response. It seems that this issue come and goes at my machine, I can't really reproduce every time. Guess I will close this issue until I can describe what exactly happens.
