### ISSUE TITLE
Choose a code formatter, format the code, and enforce in CI

### ISSUE THREAD

**Issue by nateberkopec** [MiniProfiler/rack-mini-profiler#562]
See previous attempt at #473

**Comment by keshavbiswa** [comment]
Prettier/Rubocop?

**Comment by keshavbiswa** [comment]
The previous attempt is using prettier_rb but I'd prefer rubocop. Lmk what you think @nateberkopec .

**Comment by keshavbiswa** [comment]
Nevermind! Rubocop already exists. So it's prettier then

**Comment by nateberkopec** [comment]
Ah nevermind, no idea that rubocop was already in the repo. This can be closed.
