### ISSUE TITLE
Give an option to precompile includes.css

### ISSUE THREAD

**Issue by Crystark** [MiniProfiler/rack-mini-profiler#60]
Hi,

In our production environment, the following file returns a 404: `/mini-profiler-resources/includes.css`

The reason to this is that all our static resources (css, js, images...) are managed by a content delivery server that catches the requests based on the extension of the file and fetches the file directly on disc to optimize the delivery of those.
As `includes.css` isn't actually in the assets directory, it fails to fetch it.

Would it be possible to give an option to allow this file to be precompiled alongside the other CSS files when using `rake assets:precompile` ?

Thanks

**Comment by pencilcheck** [comment]
+1

**Comment by 5minpause** [comment]
+1
Is there any development for this issue?
Would it be an option to include the .css files in the assets pipeline if present?

**Comment by stiller-leser** [comment]
Has there been any work on this issue? We are facing the same issue when trying to integrate the profiler into an Rails-app with asset-pipeline. It won't get the include.js - had a look at gemifying it, but there are a lot of changes needed. Hard to do, if you don't know the code status.

**Comment by SamSaffron** [comment]
totally open to allowing the assets to be included via sprockets, it should be fairly straight forward to just move stuff around a bit to make this workable no?

**Comment by factcondenser** [comment]
I believe this issue has been addressed per the merged PR mentioned above ☝️. @SamSaffron - should be safe to close this issue unless anyone objects?

**Comment by SamSaffron** [comment]
thanks @factcondenser closed.
