### ISSUE TITLE
How to hide in staging environment unless I explicitly run authorize_request?

### ISSUE THREAD

**Issue by xanview** [MiniProfiler/rack-mini-profiler#67]
How would I hide rack-mini-profiler in staging unless I explicitly run Rack::MiniProfiler.authorize_request?

it seems the "staging" environment is for some reason handled like the development environment and rack_mini_profiler is always displayed.

**Comment by jonathanhefner** [comment]
I believe this may have been fixed by #239.

**Comment by SamSaffron** [comment]
Yep, I think our documentation for auth modes is much better now.
