### ISSUE TITLE
Not showing in Rails 4

### ISSUE THREAD

**Issue by abuisman** [MiniProfiler/rack-mini-profiler#70]
When I include the gem in my rails app the profiler is not shown. However, the javascript is included and the div is created for the widget, but the final content is empty.

I tried adding `Rack::MiniProfiler.authorize_request` in a before_filter in my application controller: no dice.

I tried creating an initializer and add `require: false` in the gem file as described in the README: no profiler.

I am using puma, rails 4.0.1, and ruby ruby 2.0.0p247

Any tips?

**Comment by akshetpandey** [comment]
+1, removing oj_mimic_json and following what @hakunin said solved the issue.

**Comment by pencilcheck** [comment]
+1, removing oj_mimic_json works. It sucks because it was suppose to make json serialization faster.

**Comment by SamSaffron** [comment]
this is all very strange can someone write a test case that fails here, somehow ojs json implementation is lacking and its hurting us here.

**Comment by akshetpandey** [comment]
The issue is that OJ doesn't handle circular reference in objects. For example:

```ruby
2.1.5 :001 > require 'oj'
 => true
2.1.5 :002 > require 'oj_mimic_json'
 => true
2.1.5 :082 > b = {a: {}}
 => {:a=>{}}
2.1.5 :083 > b[:a] = b
 => {:a=>{...}}
2.1.5 :084 > b.to_json
NoMemoryError: Too deeply nested.

	from (irb):84:in `to_json'
	from (irb):84
	from /Users/akshet/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
```

**Comment by pencilcheck** [comment]
Oj.default_options = {
  :mode => :compat,
  :use_to_json => true
}

This works for me for circular references

**Comment by SamSaffron** [comment]
before any of this can someone help isolate the circular ref, so we can remove it, we don't really need it in our persistence structure.

**Comment by DavidRagone** [comment]
I also had to both remove Deflator and oj_mimic_json to get this to work. Ruby 2.2, Rails 4.2.1

**Comment by eggie5** [comment]
+1 for removing `oj_mimic_json` gem.

**Comment by kevinjalbert** [comment]
Just wanted to chime in that I encountered the same issue. I had to remove the `oj_mimic_json` gem for this to work.

The solution that @pencilcheck suggested didn't work for me.

**Comment by jhubert** [comment]
I didn't have the `oj_mimic_json` gem, but removing `heroku-deflator` worked for me.

**Comment by thatpixguy** [comment]
We were missing the badge, and it turned out it was because we were using ```heroku_rails_deflate```. Using ```heroku-deflater``` seems to not break the badge.

**Comment by Ch4s3** [comment]
This still happens for me

**Comment by steverob** [comment]
Same issue for me. Described more at #134 (https://github.com/MiniProfiler/rack-mini-profiler/issues/134#issuecomment-230160744)

**Comment by steverob** [comment]
@SamSaffron Here is a fresh Rails app (4.2.6 / 2.3.1) where this has been reproduced. https://github.com/steverob/miniprofiler-production-test

**Comment by dgynn** [comment]
@steverob I ran your test app and was not able to reproduce the problem. The mini profiler showed up just fine on the second request.

**Comment by steverob** [comment]
Really?  :( let me check again.

--
Regards
Steve Robinson

**Comment by steverob** [comment]
@dgynn yes you're right. Upon second request it shows up. No such luck for my app though. Same environment. Any ideas?

**Comment by steverob** [comment]
@dgynn sorry my bad. I did not restart server after adding the `authorize_request` call :(. Code reloading!!

Thanks.

**Comment by newdark** [comment]
Here is a way to get around minprofile in development mode. If you are using the oj gem and not the oj_mimic_json which really is just a small bit of code.
#### oj-mimic-son-1.0.1 (lib/oj_mimic_json.rb)
```ruby
require 'oj'

Oj.mimic_JSON()
# Requiring json here seems to stop conflicts when requiring json in other files.
begin
  require 'json'
rescue Exception
  # ignore
end
```

#### config/initializers/oj.rb
```ruby
require 'oj'

Oj.default_options = {
  mode: :compat
}

# Should be able to remove this(Rails.env.development?) once a update comes out
# https://github.com/MiniProfiler/rack-mini-profiler/pull/250
Oj.mimic_JSON unless Rails.env.development?
```

Basically I am turning off the OJ system in development as it is the only time we are using to try and backtrace slow queries.

**Comment by nruth** [comment]
Disabling Rack::Deflater in development fixed things for me.

```
WhateverApp::Application.configure do
  config.middleware.insert_before ActionDispatch::Static, Rack::Deflater
end
```

Commenting that out and restarting `rails s` made the profiler work in development on rails 4.2.6 ruby 2.3.1 with the Gemfile-only default setup.

**Comment by nateberkopec** [comment]
Closing as stale. Linking #16.
