### ISSUE TITLE
backtrace_filter Doesn't Exist

### ISSUE THREAD

**Issue by dyeje** [MiniProfiler/rack-mini-profiler#76]
The backtrace_filter config listed does not exist.  You get a NoMethodError when defining it in the config file.

**Comment by tonyrosario** [comment]
Just ran into this.  I found the following methods on the config:

:backtrace_ignores
:backtrace_ignores
:backtrace_includes
:backtrace_includes
:backtrace_remove
:backtrace_remove
:backtrace_threshold_ms
:backtrace_threshold_ms

**Comment by SamSaffron** [comment]
be sure to submit a PR that documents this

**Comment by tonyrosario** [comment]
will do @SamSaffron
