### ISSUE TITLE
Breaks apps which use require.js to load jquery

### ISSUE THREAD

**Issue by purcell** [MiniProfiler/rack-mini-profiler#77]
`rack-mini-profiler` presumably loads jquery directly for its own use, but if the rest of the app uses `require.js` to load `jquery` as an AMD module, the module does not get defined properly. I guess that jquery detects that it is already loaded.

Not sure what a workaround would be, other than cutting out the `jquery` dependency from `rack-mini-profiler`, but perhaps it would at least be worthwhile cautioning `require.js` users.

**Comment by reustmd** [comment]
@purcell @yoda I realize this is old, but I was wondering if anything else happened with this?

**Comment by purcell** [comment]
@reustmd Unsure, sorry - I just stopped using `rack-mini-profiler`.

**Comment by reustmd** [comment]
@purcell no worries. Do you use another tool instead?

**Comment by purcell** [comment]
Not a similar tool, but I use NewRelic's development mode when I'm actively profiling site performance.

**Comment by rennhak** [comment]
+1

**Comment by SamSaffron** [comment]
I want to sort this out, but am going to need some help here, open to amending mp to detect requirejs and try to use it instead.

**Comment by yoda** [comment]
I actually gave up on this we have moved to webpack instead with mixture of cjs and es6 import syntax. Miniprof seems to work in this environment.

**Comment by fuchse** [comment]
+1

**Comment by MichaelSp** [comment]
with the raise of https://github.com/rails/webpacker this really becomes a show stopper... Looks like I'm forced to live without this nice little gem 😭

**Comment by SamSaffron** [comment]
I am open to cutting out jquery here. Maybe that is the best long term solution.

**Comment by jonathanhefner** [comment]
This has been fixed by #399.

**Comment by SamSaffron** [comment]
Confirmed as fixed, I love that we no longer have a jQuery dependency!
