### ISSUE TITLE
MiniProfiler not Working on Rails 2.3.18

### ISSUE THREAD

**Issue by JohnSundarraj** [MiniProfiler/rack-mini-profiler#79]
Hey there, I would like to that for this opensource project. I've tried miniprofiler on Rails 4 , it worked fine. 

But i tried the same on Rails 2.3.18 including your patch on environment.rb, but.... it did'nt work. Need help on this, It would be great if i get this working on Rails 2.3.18. Thanks.

**Comment by sergiotapia** [comment]
Same problem here. Any help?

**Comment by SamSaffron** [comment]
Sorry, closing as will not support, Rails 2 is pretty much abandoned at this point in time.
