### ISSUE TITLE
Chrome javascript error: Refused to get unsafe header "X-MiniProfiler-Ids"

### ISSUE THREAD

**Issue by dy-dx** [MiniProfiler/rack-mini-profiler#95]
Browser: Chrome 36.0.1985.143 on OSX
Rails: 3.2.19
rack-mini-profiler: 0.9.2

![image](https://cloud.githubusercontent.com/assets/1074881/3983220/8151b29e-287d-11e4-82f2-42f9f02d642d.png)

**Comment by diffractometer** [comment]
I'm seeing this anyone else?

**Comment by covaithe** [comment]
I started seeing this when using angular with cross origin resources and CORS.  See for example http://jaketrent.com/post/expose-http-headers-in-cors/

**Comment by steverob** [comment]
Yeah. Any solution for this?

**Comment by kbrock** [comment]
This looks like it will need to tie into cors of the main app.
Or at least provide partial cors support for at least own responses

**Comment by steverob** [comment]
I added this - `headers['Access-Control-Expose-Headers'] = 'X-MiniProfiler-Ids'`, still does not seem to work at all.

![screenshot from 2016-07-02 17 10 53](https://cloud.githubusercontent.com/assets/1220480/16540165/fd4e896c-4077-11e6-94ae-0625952156a6.png)

**Comment by kbrock** [comment]
@steverob What gem are you using that introduced cors?
I wonder if we can detect this gem and add a rule for this page

**Comment by ahmedgalal1** [comment]
Add this header to response "Access-Control-Expose-Headers"

Response.AddHeader("Access-Control-Expose-Headers", "X-MiniProfiler-Ids");

**Comment by justin808** [comment]
I'm using rack-cors and the following line did not work:

```ruby
    headers["Access-Control-Expose-Headers"] = "X-MiniProfiler-Ids"
```

**Comment by lleolin** [comment]
For me, this error seems to stem from using Invoker. Not entirely sure how Invoker operates, but it's like it's proxying <domain>.<tld> to localhost:<port>. If I access my app's dev server through localhost:<port> there is no error, which makes sense. There's something Invoker must be doing or not doing differently compared to e.g. puma-dev or pow.

Can't speak for everyone's situation though.

**Comment by boo68120** [comment]
> I added this - `headers['Access-Control-Expose-Headers'] = 'X-MiniProfiler-Ids'`, still does not seem to work at all.
> 
> ![screenshot from 2016-07-02 17 10 53](https://cloud.githubusercontent.com/assets/1220480/16540165/fd4e896c-4077-11e6-94ae-0625952156a6.png)

recently I faced cross origin error like s3 needs ro verify the region :3000 so we added the cross origin options in s3 and it got worked

**Comment by gencer** [comment]
Don't like the +1's but Seeing the same error.

**Comment by SamSaffron** [comment]
Yes we are aware of this @OsamaSayegh  is investigating a fix here.

**Comment by OsamaSayegh** [comment]
This was fixed in https://github.com/MiniProfiler/rack-mini-profiler/commit/d62736ecb4f519b5048bf4a3435ba1f1228a3d01.
