### ISSUE TITLE
maxTracesToShow is not documented

### ISSUE THREAD

**Issue by jjb** [MiniProfiler/rack-mini-profiler#98]
This has caused me a good amount of confusion and grief.

Its value is not documented and also not configurable.

IMO:

1. it should be configurable
2. the default value should be mentioned in the readme
3. the default value should be much higher or unlimited

what is the value in limiting to 10? especially since it isn't sorted by decreasing time.

**Comment by SamSaffron** [comment]
fixed via https://github.com/MiniProfiler/rack-mini-profiler/commit/77b2c67105278e3eada60da942b8f2aabca36bec
